filechampion4j: dev.filechampion.filechampion4j.PluginsHelper.StepConfig Class Reference
dev.filechampion.filechampion4j.PluginsHelper.StepConfig Class Reference
Public Member Functions
boolean isRunBefore ()
void setRunBefore (boolean runBefore)
boolean isRunAfter ()
void setRunAfter (boolean runAfter)
CliPluginHelper getCliPluginHelper ()
void setCliPluginHelper (CliPluginHelper cliPluginHelper)
String getName ()
void setName (String name)
String getType ()
void setType (String type)
String getEndpoint ()
void setEndpoint (String endpoint)
int getTimeout ()
void setTimeout (int timeout)
String getOnFail ()
void setOnFail (String onFail)
String getResponse ()
void setResponse (String response)
String getMethod ()
void setMethod (String method)
JSONObject getHeaders ()
void setHeaders (JSONObject headers)
JSONObject getBody ()
void setBody (JSONObject body)
int getHttpPassCode ()
void setHttpPassCode (int httpPassCode)
int getHttpFailCode ()
void setHttpFailCode (int httpFailCode)
String getCredsPath ()
void setCredsPath (String credsPath)
Private Attributes
String name
String type
String endpoint
int timeout
String onFail
String response
String method
JSONObject headers
JSONObject body
int httpPassCode
int httpFailCode
String credsPath
CliPluginHelper cliPluginHelper
boolean runBefore
boolean runAfter
Detailed Description
Set and return a single step configuration.
Returns
(StepConfig) a StepConfig object
Definition at line 108 of file PluginsHelper.java.
Member Function Documentation
getBody()
JSONObject dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getBody ()
Definition at line 213 of file PluginsHelper.java.
{
            return body;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.body.
getCliPluginHelper()
CliPluginHelper dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getCliPluginHelper ()
Definition at line 141 of file PluginsHelper.java.
{
            return cliPluginHelper;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.cliPluginHelper.
getCredsPath()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getCredsPath ()
Definition at line 237 of file PluginsHelper.java.
{
            return credsPath;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.credsPath.
getEndpoint()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getEndpoint ()
Definition at line 165 of file PluginsHelper.java.
{
            return endpoint;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.endpoint.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper().
getHeaders()
JSONObject dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHeaders ()
Definition at line 205 of file PluginsHelper.java.
{
            return headers;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.headers.
getHttpFailCode()
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHttpFailCode ()
Definition at line 229 of file PluginsHelper.java.
{
            return httpFailCode;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpFailCode.
getHttpPassCode()
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHttpPassCode ()
Definition at line 221 of file PluginsHelper.java.
{
            return httpPassCode;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpPassCode.
getMethod()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getMethod ()
Definition at line 197 of file PluginsHelper.java.
{
            return method;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.method.
getName()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getName ()
Definition at line 149 of file PluginsHelper.java.
{
            return name;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.name.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper(), and dev.filechampion.filechampion4j.CliPluginHelper.execute().
getOnFail()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getOnFail ()
Definition at line 181 of file PluginsHelper.java.
{
            return onFail;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.onFail.
getResponse()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getResponse ()
Definition at line 189 of file PluginsHelper.java.
{
            return response;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.response.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper().
getTimeout()
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getTimeout ()
Definition at line 173 of file PluginsHelper.java.
{
            return timeout;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.timeout.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper().
getType()
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getType ()
Definition at line 157 of file PluginsHelper.java.
{
            return type;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.type.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
isRunAfter()
boolean dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunAfter ()
Definition at line 133 of file PluginsHelper.java.
{
            return runAfter;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runAfter.
Referenced by dev.filechampion.filechampion4j.FileValidator.loadPlugins().
isRunBefore()
boolean dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunBefore ()
Definition at line 125 of file PluginsHelper.java.
{
            return runBefore;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runBefore.
Referenced by dev.filechampion.filechampion4j.FileValidator.loadPlugins().
setBody()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setBody (JSONObject body)
Definition at line 217 of file PluginsHelper.java.
{
            this.body = body;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.body.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setCliPluginHelper()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCliPluginHelper (CliPluginHelper cliPluginHelper)
Definition at line 145 of file PluginsHelper.java.
{
            this.cliPluginHelper = cliPluginHelper;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.cliPluginHelper.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setCredsPath()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCredsPath (String credsPath)
Definition at line 241 of file PluginsHelper.java.
{
            this.credsPath = credsPath;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.credsPath.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setEndpoint()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setEndpoint (String endpoint)
Definition at line 169 of file PluginsHelper.java.
{
            this.endpoint = endpoint;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.endpoint.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setHeaders()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHeaders (JSONObject headers)
Definition at line 209 of file PluginsHelper.java.
{
            this.headers = headers;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.headers.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setHttpFailCode()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpFailCode (int httpFailCode)
Definition at line 233 of file PluginsHelper.java.
{
            this.httpFailCode = httpFailCode;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpFailCode.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setHttpPassCode()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpPassCode (int httpPassCode)
Definition at line 225 of file PluginsHelper.java.
{
            this.httpPassCode = httpPassCode;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpPassCode.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setMethod()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setMethod (String method)
Definition at line 201 of file PluginsHelper.java.
{
            this.method = method;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.method.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setName()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setName (String name)
Definition at line 153 of file PluginsHelper.java.
{
            this.name = name;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.name.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setOnFail()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setOnFail (String onFail)
Definition at line 185 of file PluginsHelper.java.
{
            this.onFail = onFail;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.onFail.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setResponse()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setResponse (String response)
Definition at line 193 of file PluginsHelper.java.
{
            this.response = response;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.response.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setRunAfter()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunAfter (boolean runAfter)
Definition at line 137 of file PluginsHelper.java.
{
            this.runAfter = runAfter;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runAfter.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setRunBefore()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunBefore (boolean runBefore)
Definition at line 129 of file PluginsHelper.java.
{
            this.runBefore = runBefore;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runBefore.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setTimeout()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setTimeout (int timeout)
Definition at line 177 of file PluginsHelper.java.
{
            this.timeout = timeout;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.timeout.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
setType()
void dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setType (String type)
Definition at line 161 of file PluginsHelper.java.
{
            this.type = type;
        }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.type.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
Member Data Documentation
body
JSONObject dev.filechampion.filechampion4j.PluginsHelper.StepConfig.body private
Definition at line 117 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getBody(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setBody().
cliPluginHelper
CliPluginHelper dev.filechampion.filechampion4j.PluginsHelper.StepConfig.cliPluginHelper private
Definition at line 121 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getCliPluginHelper(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCliPluginHelper().
credsPath
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.credsPath private
Definition at line 120 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getCredsPath(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCredsPath().
endpoint
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.endpoint private
Definition at line 111 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getEndpoint(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setEndpoint().
headers
JSONObject dev.filechampion.filechampion4j.PluginsHelper.StepConfig.headers private
Definition at line 116 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHeaders(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHeaders().
httpFailCode
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpFailCode private
Definition at line 119 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHttpFailCode(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpFailCode().
httpPassCode
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.httpPassCode private
Definition at line 118 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getHttpPassCode(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpPassCode().
method
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.method private
Definition at line 115 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getMethod(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setMethod().
name
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.name private
Definition at line 109 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getName(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setName().
onFail
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.onFail private
Definition at line 113 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getOnFail(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setOnFail().
response
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.response private
Definition at line 114 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getResponse(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setResponse().
runAfter
boolean dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runAfter private
Definition at line 123 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunAfter(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunAfter().
runBefore
boolean dev.filechampion.filechampion4j.PluginsHelper.StepConfig.runBefore private
Definition at line 122 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunBefore(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunBefore().
timeout
int dev.filechampion.filechampion4j.PluginsHelper.StepConfig.timeout private
Definition at line 112 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getTimeout(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setTimeout().
type
String dev.filechampion.filechampion4j.PluginsHelper.StepConfig.type private
Definition at line 110 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getType(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setType().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/PluginsHelper.java