filechampion4j: dev.filechampion.filechampion4j.SH256Calculate Class Reference
dev.filechampion.filechampion4j.SH256Calculate Class Reference
Classes
class ChecksumTask
Public Member Functions
SH256Calculate (byte[] inputData) throws IllegalArgumentException
byte[] getChecksum () throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException
Private Member Functions
byte[] calculateSmallSHA256Checksum () throws NoSuchAlgorithmException
byte[] calculateSHA256Checksum () throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException
Private Attributes
final byte[] inputData
int byteSize
Static Private Attributes
static final int MIN_CHUNK_SIZE = 1024 * 1024
static final int MAX_CHUNK_SIZE = 5 * 1024 * 1024
Detailed Description
This class is used to calculate the SHA256 checksum of a file. It is optimized for large files and uses multiple threads to calculate the checksum in parallel.
Definition at line 20 of file SH256Calculate.java.
Constructor & Destructor Documentation
SH256Calculate()
dev.filechampion.filechampion4j.SH256Calculate.SH256Calculate (byte[] inputData) throws IllegalArgumentException
Creates a new instance of the SH256Calculate class.
Parameters
inputData (bytep[]) The input data to calculate the checksum for.
Exceptions
IllegalArgumentException Thrown if the input data is null or empty.
Definition at line 31 of file SH256Calculate.java.
{
        if (inputData == null || inputData.length == 0) {
            throw new IllegalArgumentException("Input data must contain at least one byte.");
        }
        this.inputData = inputData;
        this.byteSize = inputData.length;
    }
References dev.filechampion.filechampion4j.SH256Calculate.inputData.
Member Function Documentation
calculateSHA256Checksum()
byte[] dev.filechampion.filechampion4j.SH256Calculate.calculateSHA256Checksum () throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException private
Calculates the SHA256 checksum for large input data.
Returns
(byte[]) The SHA256 checksum.
Exceptions
NoSuchAlgorithmException Thrown if the SHA256 algorithm is not available.
InterruptedException Thrown if the thread is interrupted.
ExecutionException Thrown if the execution fails.
IOException Thrown if an I/O error occurs.
Definition at line 71 of file SH256Calculate.java.
{
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        ByteArrayInputStream bais = new ByteArrayInputStream(inputData);
        int numProcessors = Runtime.getRuntime().availableProcessors();
        ThreadPoolExecutor executor = new ThreadPoolExecutor(numProcessors, numProcessors,
                0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>());
        long fileSize = inputData.length;
        long chunkSize = Math.max(MIN_CHUNK_SIZE, Math.min(fileSize / numProcessors, MAX_CHUNK_SIZE));
        int numChunks = (int) Math.ceil((double) fileSize / chunkSize);
        byte[] buffer = new byte[(int) chunkSize];
        List<Future<?>> futures = new ArrayList<>(numChunks);
        for (int i = 0; i < numChunks; i++) {
            int bytesRead = bais.read(buffer, 0, (int) Math.min(chunkSize, fileSize - i * chunkSize));
            Future<?> future = executor.submit(new ChecksumTask(md, buffer, bytesRead));
            futures.add(future);
        }
        // wait for all futures to complete
        for (Future<?> future : futures) {
            future.get();
        }
        executor.shutdown();
        bais.close();
        return md.digest();
    }
References dev.filechampion.filechampion4j.SH256Calculate.inputData, dev.filechampion.filechampion4j.SH256Calculate.MAX_CHUNK_SIZE, and dev.filechampion.filechampion4j.SH256Calculate.MIN_CHUNK_SIZE.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.getChecksum().
calculateSmallSHA256Checksum()
byte[] dev.filechampion.filechampion4j.SH256Calculate.calculateSmallSHA256Checksum () throws NoSuchAlgorithmException private
Calculates the SHA256 checksum for small input data.
Returns
(byte[]) The SHA256 checksum.
Exceptions
NoSuchAlgorithmException Thrown if the SHA256 algorithm is not available.
Definition at line 59 of file SH256Calculate.java.
{
        return MessageDigest.getInstance("SHA-256").digest(inputData);
    }
References dev.filechampion.filechampion4j.SH256Calculate.inputData.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.getChecksum().
getChecksum()
byte[] dev.filechampion.filechampion4j.SH256Calculate.getChecksum () throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException
Calculates the SHA256 checksum for the input data.
Returns
(byte[]) The SHA256 checksum.
Exceptions
NoSuchAlgorithmException Thrown if the SHA256 algorithm is not available.
InterruptedException Thrown if the thread is interrupted.
ExecutionException Thrown if the execution fails.
IOException Thrown if an I/O error occurs.
Definition at line 47 of file SH256Calculate.java.
{
        if (byteSize < MIN_CHUNK_SIZE * 2) {
            return calculateSmallSHA256Checksum();
        }
        return calculateSHA256Checksum() ;
    }
References dev.filechampion.filechampion4j.SH256Calculate.byteSize, dev.filechampion.filechampion4j.SH256Calculate.calculateSHA256Checksum(), dev.filechampion.filechampion4j.SH256Calculate.calculateSmallSHA256Checksum(), and dev.filechampion.filechampion4j.SH256Calculate.MIN_CHUNK_SIZE.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.calculateChecksum(), and dev.filechampion.filechampion4j.FileValidator.calculateChecksum().
Member Data Documentation
byteSize
int dev.filechampion.filechampion4j.SH256Calculate.byteSize private
Definition at line 24 of file SH256Calculate.java.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.getChecksum().
inputData
final byte [] dev.filechampion.filechampion4j.SH256Calculate.inputData private
Definition at line 23 of file SH256Calculate.java.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.SH256Calculate(), dev.filechampion.filechampion4j.SH256Calculate.calculateSHA256Checksum(), and dev.filechampion.filechampion4j.SH256Calculate.calculateSmallSHA256Checksum().
MAX_CHUNK_SIZE
final int dev.filechampion.filechampion4j.SH256Calculate.MAX_CHUNK_SIZE = 5 * 1024 * 1024 static private
Definition at line 22 of file SH256Calculate.java.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.calculateSHA256Checksum().
MIN_CHUNK_SIZE
final int dev.filechampion.filechampion4j.SH256Calculate.MIN_CHUNK_SIZE = 1024 * 1024 static private
Definition at line 21 of file SH256Calculate.java.
Referenced by dev.filechampion.filechampion4j.SH256Calculate.calculateSHA256Checksum(), and dev.filechampion.filechampion4j.SH256Calculate.getChecksum().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/SH256Calculate.java