filechampion4j: dev.filechampion.filechampion4j.PluginsHelper Class Reference
dev.filechampion.filechampion4j.PluginsHelper Class Reference
Classes
class PluginConfig
class StepConfig
Public Member Functions
PluginsHelper (JSONObject plugins)
Map< String, PluginConfig > getPluginConfigs ()
Private Attributes
JSONObject plugins
Detailed Description
This class is used to fetch and load the Json configuration data for all plugins. Allowing the Json configuration data to be loaded once and then used by all plugins. Returns a list of PluginConfig objects.
Definition at line 12 of file PluginsHelper.java.
Constructor & Destructor Documentation
PluginsHelper()
dev.filechampion.filechampion4j.PluginsHelper.PluginsHelper (JSONObject plugins)
Constructor
Parameters
plugins (JSONObject) a JSONObject containing all plugins
Returns
(PluginsHelper) a PluginsHelper object
Definition at line 20 of file PluginsHelper.java.
{
        this.plugins = plugins;
    }
References dev.filechampion.filechampion4j.PluginsHelper.plugins.
Member Function Documentation
getPluginConfigs()
Map< String, PluginConfig > dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs ()
Returns a list of PluginConfig objects.
Returns
(List<PluginConfig>) a list of PluginConfig objects
Definition at line 28 of file PluginsHelper.java.
{
        HashMap<String, PluginConfig> pluginConfigs = new HashMap<>();
        Map<String, StepConfig> stepConfigs = new HashMap<>();
        for (String pluginName : plugins.keySet()) {
            JSONObject plugin = plugins.getJSONObject(pluginName);
            PluginConfig pluginConfig = new PluginConfig();
            pluginConfig.setName(pluginName);
            for (String stepName : plugin.keySet()) {
                JSONObject step = plugin.getJSONObject(stepName);
                StepConfig stepConfig = new StepConfig();
                String pluginStepName = pluginName + "." + stepName.substring(0, stepName.lastIndexOf('.'));
                stepConfig.setName(pluginStepName);
                stepConfig.setType(step.getString("type"));
                stepConfig.setRunBefore(step.optBoolean("run_before"));
                stepConfig.setRunAfter(step.optBoolean("run_after"));
                stepConfig.setCredsPath(step.optString("creds_path"));
                stepConfig.setTimeout(step.getInt("timeout"));
                stepConfig.setOnFail(step.getString("on_timeout_or_fail"));
                stepConfig.setEndpoint(step.getString("endpoint"));
                stepConfig.setResponse(step.getString("response"));
                switch (stepConfig.getType()) {
                    case "cli":
                        CliPluginHelper cliPluginStep = new CliPluginHelper(stepConfig);
                        stepConfig.setCliPluginHelper(cliPluginStep);
                        stepConfigs.put(pluginStepName, stepConfig);
                        continue;
                    case "http":
                        stepConfig.setMethod(step.optString("method"));
                        stepConfig.setHeaders(step.optJSONObject("headers"));
                        stepConfig.setBody(step.optJSONObject("body"));
                        stepConfig.setHttpPassCode(step.optInt("http_pass_code"));
                        stepConfig.setHttpFailCode(step.optInt("http_fail_code"));
                        stepConfigs.put(pluginStepName, stepConfig);
                        continue;
                    default:
                        continue;
                }
            }
            pluginConfig.setStepConfigs(stepConfigs);
            pluginConfigs.put(pluginName, pluginConfig);
        }
        return pluginConfigs;
    }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getType(), dev.filechampion.filechampion4j.PluginsHelper.plugins, dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setBody(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCliPluginHelper(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setCredsPath(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setEndpoint(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHeaders(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpFailCode(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setHttpPassCode(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setMethod(), dev.filechampion.filechampion4j.PluginsHelper.PluginConfig.setName(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setName(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setOnFail(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setResponse(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunAfter(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setRunBefore(), dev.filechampion.filechampion4j.PluginsHelper.PluginConfig.setStepConfigs(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setTimeout(), and dev.filechampion.filechampion4j.PluginsHelper.StepConfig.setType().
Referenced by dev.filechampion.filechampion4j.FileValidator.loadPlugins().
Member Data Documentation
plugins
JSONObject dev.filechampion.filechampion4j.PluginsHelper.plugins private
Definition at line 13 of file PluginsHelper.java.
Referenced by dev.filechampion.filechampion4j.PluginsHelper.PluginsHelper(), and dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/PluginsHelper.java