filechampion4j: dev.filechampion.filechampion4j.CredentialsManager Class Reference
dev.filechampion.filechampion4j.CredentialsManager Class Reference
Public Member Functions
CredentialsManager (Path credsPath, List< String > credsNamesList) throws IllegalArgumentException
void setExpirationTime (long expirationTime) throws IllegalArgumentException
char[] getCredentials (String credsName) throws IllegalArgumentException, IOException
Private Member Functions
char[] getCredFileChars (Path credFilePath) throws IOException
void logInfo (StringBuilder message)
void logSevere (StringBuilder message)
void logFine (StringBuilder message)
void generateRandomString ()
char[] addSalt (char[] charString)
void checkCredExpiration ()
Private Attributes
StringBuilder logMessage = new StringBuilder()
long credsExpirationTime = 300000
Path credsPath
List< String > credsNamesList
List< char[]> credsList = new LinkedList<>()
Map< String, Map< Integer, Long > > credsMap = new HashMap<>()
SecureRandom random = new SecureRandom()
String randomString = ""
int randomStringIndex = 0
boolean expirationTimerStarted = false
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(CredentialsManager.class.getName())
Detailed Description
CredentialsManager class is used to manage any credendials that are needed for plugins, such as API keys, etc.
Definition at line 27 of file CredentialsManager.java.
Constructor & Destructor Documentation
CredentialsManager()
dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager (Path credsPath, List< String > credsNamesList) throws IllegalArgumentException
Constructor for CredentialsManager class.
Parameters
credsPath (Path) - Path to the directory where the credentials files are stored.
credsNamesList (List <String>) - List of the names of the credentials names/files.
Exceptions
IllegalArgumentException - If the credsPath is null or does not exist, or if the credsNamesList is null or empty, or if any of the credentials files are not found.
Definition at line 59 of file CredentialsManager.java.
{
        if (credsPath == null || !Files.exists(credsPath)) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Defined credentials path was not found."));
            throw new IllegalArgumentException("Defined credentials path was not found.");
        }
        if (credsNamesList == null || credsNamesList.isEmpty()) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Defined credentials list was empty."));
            throw new IllegalArgumentException("Defined credentials list was empty.");
        }
        this.credsPath = credsPath;
        // Check that all creds files exist
        for (String credsName : credsNamesList) {
            Path credFilePath = credsPath.resolve(credsName);
            if (!Files.exists(credFilePath)) {
                logSevere(logMessage.replace(0, logMessage.length() ,"Credentials file ").append(credsName).append(" was not found."));
                throw new IllegalArgumentException("Credentials file " + credsName + " was not found.");
            }
        }
        this.credsNamesList = credsNamesList;
        logInfo(logMessage.replace(0, logMessage.length() ,"CredentialsManager initialized."));
    }
References dev.filechampion.filechampion4j.CredentialsManager.credsNamesList, dev.filechampion.filechampion4j.CredentialsManager.credsPath, dev.filechampion.filechampion4j.CredentialsManager.logInfo(), dev.filechampion.filechampion4j.CredentialsManager.logMessage, and dev.filechampion.filechampion4j.CredentialsManager.logSevere().
Member Function Documentation
addSalt()
char[] dev.filechampion.filechampion4j.CredentialsManager.addSalt (char[] charString) private
Add unique salt to a given string.
Parameters
charString (char[]) - The string to add salt to.
Returns
(char[]) - The salted string.
Definition at line 223 of file CredentialsManager.java.
{
        if (this.randomStringIndex + charString.length > this.randomString.length()) {
            generateRandomString();
            this.randomStringIndex = 0;
        }
        char[] saltChars = randomString.substring(randomStringIndex, randomStringIndex + charString.length).toCharArray();
        char[] saltedString = new char[charString.length * 2];
        int index = 0;
        for (int i = 0; i < charString.length; i++) {
            saltedString[index++] = charString[i];
            saltedString[index++] = saltChars[i];
        }
        this.randomStringIndex += saltChars.length;
        return saltedString;
    }
checkCredExpiration()
void dev.filechampion.filechampion4j.CredentialsManager.checkCredExpiration () private
This method is used to check if any credential is expired, and remove them from the list if it is.
Definition at line 242 of file CredentialsManager.java.
{
        logFine(logMessage.replace(0, logMessage.length() ,"Checking for expired credentials."));
        List<String> expiredKeys = new ArrayList<>();
        for (Map.Entry<String, Map<Integer, Long>> entry : this.credsMap.entrySet()) {
            String key = entry.getKey();
            Integer credPosition = entry.getValue().keySet().iterator().next();
            long credLastTime = entry.getValue().getOrDefault(2, credsExpirationTime);
            if (System.currentTimeMillis() - credLastTime > credsExpirationTime) {
                Arrays.fill(this.credsList.get(credPosition), '0');
                this.credsList.remove(this.credsList.get(credPosition));
                expiredKeys.add(key);
                logFine(logMessage.replace(0, logMessage.length() ,"Credentials ").append(key).append(" removed from list."));
            }
        }
        for (String key : expiredKeys) {
            this.credsMap.remove(key);
            logFine(logMessage.replace(0, logMessage.length() ,"Expired credentials metadata ").append(key).append(" removed from map."));
        }
    }
generateRandomString()
void dev.filechampion.filechampion4j.CredentialsManager.generateRandomString () private
Generate a random string of a given length
Definition at line 206 of file CredentialsManager.java.
{
        int leftLimit = 48; // numeral '0'
        int rightLimit = 122; // letter 'z'
        int targetStringLength = 2048;
        this.randomString = random.ints(leftLimit, rightLimit + 1)
        .filter(i -> (i <= 57 || i >= 65) && (i <= 90 || i >= 97))
        .limit(targetStringLength)
        .collect(StringBuilder::new, StringBuilder::appendCodePoint, StringBuilder::append)
        .toString();
        logFine(logMessage.replace(0, logMessage.length() ,"Random string generated."));
    }
getCredentials()
char[] dev.filechampion.filechampion4j.CredentialsManager.getCredentials (String credsName) throws IllegalArgumentException, IOException
This method is used to retrieve a credential from the cached credentials list or read it from the file and add it to the list.
Parameters
credsName (String) - Name of the credentials name/file to retrieve.
Returns
(char[]) - The credentials as a char[].
Exceptions
IllegalArgumentException - If the credsName is null or empty, or if the credsName is not found in the credsNamesList.
IOException - If there is an error reading the credentials file.
Definition at line 112 of file CredentialsManager.java.
{
        if (credsName == null || credsName.isEmpty()) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Credentials name was empty."));
            throw new IllegalArgumentException("Credentials name was empty.");
        }
        if (!this.credsNamesList.contains(credsName)) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Credentials name was not found."));
            throw new IllegalArgumentException("Credentials name was not found.");
        }
        if (!expirationTimerStarted) {
            setExpirationTime(this.credsExpirationTime);
            expirationTimerStarted = true;
        }
        if (!this.credsMap.containsKey(credsName)) {
            Path fullCredPath = this.credsPath.resolve(credsName);
            this.credsList.add(addSalt(this.getCredFileChars(fullCredPath)));
            logFine(logMessage.replace(0, logMessage.length() ,"Credentials ").append(credsName).append(" with salt added to list."));
            credsMap.computeIfAbsent(credsName, k -> new HashMap<>()).put(this.credsList.size() - 1, System.currentTimeMillis());
            logFine(logMessage.replace(0, logMessage.length() ,"Credentials metadata").append(credsName).append(" added to map."));
        }
        this.credsMap.get(credsName).put(2, System.currentTimeMillis());
        logFine(logMessage.replace(0, logMessage.length() ,"Credentials ").append(credsName).append(" timestamp was updated in the list."));
        return this.credsList.get(this.credsMap.get(credsName).keySet().iterator().next());
    }
getCredFileChars()
char[] dev.filechampion.filechampion4j.CredentialsManager.getCredFileChars (Path credFilePath) throws IOException private
This method is used to read a single credential file into a char[] for storage in the Map. char[] grows dynamically as the file is read using 64 byte chunks.
Parameters
credFilePath (Path) - Path to the credentials file to read.
Returns
(char[]) - The credentials as a char[].
Exceptions
IOException - If there is an error reading the credentials file.
Definition at line 145 of file CredentialsManager.java.
{
        logFine(logMessage.replace(0, logMessage.length() ,"Reading credentials from file: ").append(credFilePath.toString()));
        try (BufferedReader br = Files.newBufferedReader(Paths.get(credFilePath.toString()), Charset.defaultCharset())) {
            char[] tmpCharArray = new char[1];
            int charRead = 0;
            int position = 0;
            while((charRead = br.read()) != -1) {
                if(position == tmpCharArray.length) {
                    char[] temp = new char[tmpCharArray.length + 1];
                    System.arraycopy(tmpCharArray, 0, temp, 0, position);
                    tmpCharArray = temp;
                }
                tmpCharArray[position++] = (char) charRead;
            }
            logFine(logMessage.replace(0, logMessage.length() ,"Credentials read from file: ").append(credFilePath.toString()));
            return tmpCharArray;
        } catch (Exception e) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Error reading credentials file: ").append(e.getMessage()));
            throw new IOException("Error reading credentials file: " + e.getMessage());
        }
    }
logFine()
void dev.filechampion.filechampion4j.CredentialsManager.logFine (StringBuilder message) private
LOGGER.fine wrapper
Parameters
message (StringBuilder) - message to log
Definition at line 197 of file CredentialsManager.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message.toString());
        }
    }
logInfo()
void dev.filechampion.filechampion4j.CredentialsManager.logInfo (StringBuilder message) private
LOGGER.info wrapper
Parameters
message (String) - message to log
Definition at line 177 of file CredentialsManager.java.
{
        if (LOGGER.isLoggable(Level.INFO)) {
            LOGGER.info(message.toString());
        }
    }
Referenced by dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager(), and dev.filechampion.filechampion4j.CredentialsManager.setExpirationTime().
logSevere()
void dev.filechampion.filechampion4j.CredentialsManager.logSevere (StringBuilder message) private
LOGGER.severe wrapper
Parameters
message (String) - message to log
Definition at line 187 of file CredentialsManager.java.
{
        if (LOGGER.isLoggable(Level.SEVERE)) {
            LOGGER.severe(message.toString());
        }
    }
Referenced by dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager(), and dev.filechampion.filechampion4j.CredentialsManager.setExpirationTime().
setExpirationTime()
void dev.filechampion.filechampion4j.CredentialsManager.setExpirationTime (long expirationTime) throws IllegalArgumentException
This method allows the user to set the expiration time for credentials in milliseconds, overriding the default of 300000 (5 minutes).
Parameters
expirationTime (long) - The expiration time in milliseconds.
Exceptions
IllegalArgumentException - If the expirationTime is less than or equal to 0.
Definition at line 87 of file CredentialsManager.java.
{
        if (expirationTime <= 0) {
            logSevere(logMessage.replace(0, logMessage.length() ,"Expiration time must be greater than 0."));
            throw new IllegalArgumentException("Expiration time must be greater than 0.");
        }
        this.credsExpirationTime = expirationTime;
        logInfo(logMessage.replace(0, logMessage.length() ,"Expiration time set to ").append(expirationTime).append(" milliseconds."));
        // add timer to remove expired creds from the list
        Timer timer = new Timer();
        timer.schedule(new java.util.TimerTask() {
            @Override
            public void run() {
                checkCredExpiration();
            }
        }, credsExpirationTime, credsExpirationTime);
        logInfo(logMessage.replace(0, logMessage.length() ,"Scheduled timer to check for expired credentials every ").append(expirationTime).append(" milliseconds."));
    }
References dev.filechampion.filechampion4j.CredentialsManager.logInfo(), dev.filechampion.filechampion4j.CredentialsManager.logMessage, and dev.filechampion.filechampion4j.CredentialsManager.logSevere().
Member Data Documentation
credsExpirationTime
long dev.filechampion.filechampion4j.CredentialsManager.credsExpirationTime = 300000 private
Definition at line 43 of file CredentialsManager.java.
credsList
List<char[]> dev.filechampion.filechampion4j.CredentialsManager.credsList = new LinkedList<>() private
Definition at line 46 of file CredentialsManager.java.
credsMap
Map<String, Map<Integer, Long> > dev.filechampion.filechampion4j.CredentialsManager.credsMap = new HashMap<>() private
Definition at line 47 of file CredentialsManager.java.
credsNamesList
List<String> dev.filechampion.filechampion4j.CredentialsManager.credsNamesList private
Definition at line 45 of file CredentialsManager.java.
Referenced by dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager().
credsPath
Path dev.filechampion.filechampion4j.CredentialsManager.credsPath private
Definition at line 44 of file CredentialsManager.java.
Referenced by dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager().
expirationTimerStarted
boolean dev.filechampion.filechampion4j.CredentialsManager.expirationTimerStarted = false private
Definition at line 51 of file CredentialsManager.java.
LOGGER
final Logger dev.filechampion.filechampion4j.CredentialsManager.LOGGER = Logger.getLogger(CredentialsManager.class.getName()) static private
Definition at line 41 of file CredentialsManager.java.
logMessage
StringBuilder dev.filechampion.filechampion4j.CredentialsManager.logMessage = new StringBuilder() private
Definition at line 42 of file CredentialsManager.java.
Referenced by dev.filechampion.filechampion4j.CredentialsManager.CredentialsManager(), and dev.filechampion.filechampion4j.CredentialsManager.setExpirationTime().
random
SecureRandom dev.filechampion.filechampion4j.CredentialsManager.random = new SecureRandom() private
Definition at line 48 of file CredentialsManager.java.
randomString
String dev.filechampion.filechampion4j.CredentialsManager.randomString = "" private
Definition at line 49 of file CredentialsManager.java.
randomStringIndex
int dev.filechampion.filechampion4j.CredentialsManager.randomStringIndex = 0 private
Definition at line 50 of file CredentialsManager.java.
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/CredentialsManager.java