filechampion4j: dev.filechampion.filechampion4j.CalculateChecksum Class Reference
dev.filechampion.filechampion4j.CalculateChecksum Class Reference
Classes
class ChecksumTask
Public Member Functions
CalculateChecksum (byte[] inputData) throws IllegalArgumentException
byte[] getChecksum (String hashAlgorithm) throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException
Private Member Functions
byte[] calculateSmallChecksum ()
byte[] calculateChecksum () throws InterruptedException, ExecutionException, IOException
Private Attributes
MessageDigest md
final byte[] inputData
int byteSize
Static Private Attributes
static final int MIN_CHUNK_SIZE = 1024 * 1024
static final int MAX_CHUNK_SIZE = 3 * 1024 * 1024
Detailed Description
This class is used to calculate the checksums of a file. It is optimized for large files and uses multiple threads to calculate the checksum in parallel.
Definition at line 20 of file CalculateChecksum.java.
Constructor & Destructor Documentation
CalculateChecksum()
dev.filechampion.filechampion4j.CalculateChecksum.CalculateChecksum (byte[] inputData) throws IllegalArgumentException
Creates a new instance of the this class.
Parameters
inputData (bytep[]) The input data to calculate the checksum for.
Exceptions
IllegalArgumentException Thrown if the input data is null or empty.
Definition at line 32 of file CalculateChecksum.java.
{
        if (inputData == null || inputData.length == 0) {
            throw new IllegalArgumentException("Input data must contain at least one byte.");
        }
        this.inputData = inputData;
        this.byteSize = inputData.length;
    }
References dev.filechampion.filechampion4j.CalculateChecksum.inputData.
Member Function Documentation
calculateChecksum()
byte[] dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum () throws InterruptedException, ExecutionException, IOException private
Calculates the checksum for large input data.
Returns
(byte[]) The calculated checksum.
Exceptions
InterruptedException Thrown if the thread is interrupted.
ExecutionException Thrown if the execution fails.
IOException Thrown if an I/O error occurs.
Definition at line 72 of file CalculateChecksum.java.
{
        ByteArrayInputStream bais = new ByteArrayInputStream(inputData);
        int numProcessors = Runtime.getRuntime().availableProcessors();
        ThreadPoolExecutor executor = new ThreadPoolExecutor(numProcessors, numProcessors,
                0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<>());
        long fileSize = inputData.length;
        long chunkSize = Math.max(MIN_CHUNK_SIZE, Math.min(fileSize / numProcessors, MAX_CHUNK_SIZE));
        int numChunks = (int) Math.ceil((double) fileSize / chunkSize);
        byte[] buffer = new byte[(int) chunkSize];
        List<Future<?>> futures = new ArrayList<>(numChunks);
        for (int i = 0; i < numChunks; i++) {
            int bytesRead = bais.read(buffer, 0, (int) Math.min(chunkSize, fileSize - i * chunkSize));
            Future<?> future = executor.submit(new ChecksumTask(md, buffer, bytesRead));
            futures.add(future);
        }
        // wait for all futures to complete
        for (Future<?> future : futures) {
            future.get();
        }
        executor.shutdown();
        bais.close();
        return md.digest();
    }
References dev.filechampion.filechampion4j.CalculateChecksum.inputData, dev.filechampion.filechampion4j.CalculateChecksum.MAX_CHUNK_SIZE, dev.filechampion.filechampion4j.CalculateChecksum.md, and dev.filechampion.filechampion4j.CalculateChecksum.MIN_CHUNK_SIZE.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
calculateSmallChecksum()
byte[] dev.filechampion.filechampion4j.CalculateChecksum.calculateSmallChecksum () private
Calculates the checksum for small input data.
Returns
(byte[]) The calculated checksum.
Definition at line 61 of file CalculateChecksum.java.
{
        return md.digest(inputData);
    }
References dev.filechampion.filechampion4j.CalculateChecksum.inputData, and dev.filechampion.filechampion4j.CalculateChecksum.md.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
getChecksum()
byte[] dev.filechampion.filechampion4j.CalculateChecksum.getChecksum (String hashAlgorithm) throws NoSuchAlgorithmException, InterruptedException, ExecutionException, IOException
Calculates the checksum for the input data.
Parameters
hashAlgorithm (String) The hash algorithm to use. Must be one of: MD5, SHA-1, SHA-256, SHA-512.
Returns
(byte[]) The calculated checksum.
Exceptions
NoSuchAlgorithmException Thrown if the algorithm is not available.
InterruptedException Thrown if the thread is interrupted.
ExecutionException Thrown if the execution fails.
IOException Thrown if an I/O error occurs.
Definition at line 49 of file CalculateChecksum.java.
{
        md = MessageDigest.getInstance(hashAlgorithm);
        if (byteSize < MIN_CHUNK_SIZE * 2) {
            return calculateSmallChecksum();
        }
        return calculateChecksum() ;
    }
References dev.filechampion.filechampion4j.CalculateChecksum.byteSize, dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum(), dev.filechampion.filechampion4j.CalculateChecksum.calculateSmallChecksum(), dev.filechampion.filechampion4j.CalculateChecksum.md, and dev.filechampion.filechampion4j.CalculateChecksum.MIN_CHUNK_SIZE.
Referenced by dev.filechampion.filechampion4j.FileValidator.calculateChecksum(), and dev.filechampion.filechampion4j.CliPluginHelper.calculateChecksum().
Member Data Documentation
byteSize
int dev.filechampion.filechampion4j.CalculateChecksum.byteSize private
Definition at line 25 of file CalculateChecksum.java.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
inputData
final byte [] dev.filechampion.filechampion4j.CalculateChecksum.inputData private
Definition at line 24 of file CalculateChecksum.java.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.CalculateChecksum(), dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum(), and dev.filechampion.filechampion4j.CalculateChecksum.calculateSmallChecksum().
MAX_CHUNK_SIZE
final int dev.filechampion.filechampion4j.CalculateChecksum.MAX_CHUNK_SIZE = 3 * 1024 * 1024 static private
Definition at line 22 of file CalculateChecksum.java.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum().
md
MessageDigest dev.filechampion.filechampion4j.CalculateChecksum.md private
Definition at line 23 of file CalculateChecksum.java.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum(), dev.filechampion.filechampion4j.CalculateChecksum.calculateSmallChecksum(), and dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
MIN_CHUNK_SIZE
final int dev.filechampion.filechampion4j.CalculateChecksum.MIN_CHUNK_SIZE = 1024 * 1024 static private
Definition at line 21 of file CalculateChecksum.java.
Referenced by dev.filechampion.filechampion4j.CalculateChecksum.calculateChecksum(), and dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/CalculateChecksum.java