filechampion4j: dev.filechampion.filechampion4j.ValidationsHelper Class Reference
dev.filechampion.filechampion4j.ValidationsHelper Class Reference
Public Member Functions
ValidationsHelper (Extensions extensions)
StringBuilder getValidationResults (String fileCategory, String fileName, byte[] originalFile, String mimeString) throws IOException, SecurityException, NumberFormatException
Private Member Functions
StringBuilder doValidations () throws IOException, SecurityException, NumberFormatException
void logWarn (StringBuilder message)
void logFine (StringBuilder message)
boolean isBlank (String str)
StringBuilder checkFileSize ()
StringBuilder checkMimeType () throws IOException, SecurityException
String getFileExtension (String fileName)
StringBuilder containsMagicBytes ()
boolean containsMagicBytesProcessor (byte[] originalFileBytes, String magicBytesPattern) throws NumberFormatException
StringBuilder containsHeaderSignatures ()
boolean containsHeaderSignaturesProcessor (byte[] fileBytes, String headerSignaturesPattern) throws NumberFormatException
StringBuilder containsFooterSignatures ()
boolean containsFooterSignaturesProcessor (byte[] fileBytes, String footerSignaturesPattern) throws NumberFormatException
Path saveFileToTempDir (String fileExtension, byte[] originalFile)
Boolean deleteTempDir (Path tempFilePath)
Private Attributes
Extensions extensions
boolean failFast = false
StringBuilder sharedStringBuilder = new StringBuilder()
String fileCategory
byte[] originalFile
String mimeString
String fileExtension
String commonLogString
int responseMsgCountFail
StringBuilder sbresponseAggregationFail
int responseMsgCountSuccess
StringBuilder sbresponseAggregationSuccess
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(ValidationsHelper.class.getName())
Detailed Description
This class contains helper methods for the FileValidator class
Version
0.9.8.3
Definition at line 17 of file ValidationsHelper.java.
Constructor & Destructor Documentation
ValidationsHelper()
dev.filechampion.filechampion4j.ValidationsHelper.ValidationsHelper (Extensions extensions)
This is the constructor for the ValidationsHelper class.
Parameters
extensions (Extensions) the Extensions object containing the file validation configuration
Definition at line 37 of file ValidationsHelper.java.
{
        this.extensions = extensions;
    }
References dev.filechampion.filechampion4j.ValidationsHelper.extensions.
Member Function Documentation
checkFileSize()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize () private
Compare file size to the maximum allowed size
Returns
StringBuilder (StringBuilder) the results of the file size check
Definition at line 152 of file ValidationsHelper.java.
{
        int maxSize;
        try {
            maxSize = Integer.parseInt(extensions.getValidationValue(fileCategory, fileExtension, "max_size") != null ? extensions.getValidationValue(fileCategory, fileExtension, "max_size").toString() : "-1");
        } catch (NumberFormatException e) {
            maxSize = -1;
        }
        if ((maxSize > -1) && (originalFile.length / 1000 > maxSize || originalFile.length == 0)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid file size (")
                .append(originalFile.length / 1000)
                .append("KB) exceeds maximum allowed size (")
                .append(maxSize)
                .append("KB)")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("File size check passed, file size: ")
                .append(originalFile.length / 1000)
                .append("KB");
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.commonLogString, dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.originalFile, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, and dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
checkMimeType()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType () throws IOException, SecurityException private
Compare the file MIME type to the expected MIME type
Returns
StringBuilder (StringBuilder) the results of the MIME type check
Exceptions
IOException (IOException) if the file cannot be saved/deleted to/from a temporary directory
SecurityException (SecurityException) if the accessed to file is denied for Files.probContentType
Definition at line 187 of file ValidationsHelper.java.
{
        String mimeType = (String) extensions.getValidationValue(fileCategory, fileExtension, "mime_type");
        String fileMimeType = isBlank(mimeString) ? "" : mimeString;
        if (!isBlank(mimeType) && isBlank(fileMimeType)) {
            Path tempFile = saveFileToTempDir(fileExtension, originalFile);
            if (tempFile == null) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: checkMimeType failed: tempFile is null");
                logWarn(sharedStringBuilder);
                throw new IOException(sharedStringBuilder.toString());
            }
            try {
                fileMimeType = Files.probeContentType(tempFile);
            } catch (IOException e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: checkMimeType failed: ").append(e.getMessage());
                logWarn(sharedStringBuilder);
                throw new IOException(sharedStringBuilder.toString());
            } catch (SecurityException e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: checkMimeType failed: ").append(e.getMessage());
                logWarn(sharedStringBuilder);
                throw new SecurityException(sharedStringBuilder.toString());
            } finally {
                deleteTempDir(tempFile);
            }
        }
        if (!isBlank(mimeType) && !isBlank(fileMimeType) && !fileMimeType.equals(mimeType)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid mime_type")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Mime type check passed, mime type: ")
                .append(mimeType);
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.commonLogString, dev.filechampion.filechampion4j.ValidationsHelper.deleteTempDir(), dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.isBlank(), dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.mimeString, dev.filechampion.filechampion4j.ValidationsHelper.originalFile, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess, dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir(), dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess, and dev.filechampion.filechampion4j.ValidationsHelper.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
containsFooterSignatures()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures () private
Check if the file contains the expected footer signatures
Returns
StringBuilder (StringBuilder) the results of the footer signatures check
Definition at line 344 of file ValidationsHelper.java.
{
        String footerSignatures = (String) extensions.getValidationValue(fileCategory, fileExtension, "footer_signatures");
        if (!isBlank(footerSignatures) && !containsFooterSignaturesProcessor(originalFile, footerSignatures)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid footer_signatures")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Footer signatures check passed, footer signatures: ")
                .append(footerSignatures);
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.commonLogString, dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignaturesProcessor(), dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.isBlank(), dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.originalFile, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, and dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
containsFooterSignaturesProcessor()
boolean dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignaturesProcessor (byte[] fileBytes, String footerSignaturesPattern) throws NumberFormatException private
Check if the file contains the expected footer signatures
Parameters
fileBytes (byte[]) the file bytes of the file being validated
footerSignaturesPattern (String) the expected footer signatures of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected footer signatures, false otherwise
Definition at line 367 of file ValidationsHelper.java.
{
        if (isBlank(footerSignaturesPattern)) {
            return true;
        }
        String hexPattern = footerSignaturesPattern.replaceAll("\\p{Zs}", "");
        if (hexPattern.length() % 2 != 0) {
            hexPattern = "0" + hexPattern;
        }
        byte[] footerSignatures = new byte[hexPattern.length() / 2];
        for (int i = 0; i < hexPattern.length(); i += 2) {
            footerSignatures[i / 2] = (byte) Integer.parseInt(hexPattern.substring(i, i + 2), 16);
        }
        int footerStartIndex = fileBytes.length - footerSignatures.length -1;
        if (footerStartIndex < 0) {
            return false;
        }
        for (int i = 0; i < footerSignatures.length; i++) {
            if (fileBytes[footerStartIndex + i] != footerSignatures[i]) {
                return false;
            }
        }
        return true;
    }
References dev.filechampion.filechampion4j.ValidationsHelper.isBlank().
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures().
containsHeaderSignatures()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures () private
Check if the file contains the expected header signatures
Returns
StringBuilder (StringBuilder) the results of the header signatures check
Definition at line 297 of file ValidationsHelper.java.
{
        String headerSignatures = (String) extensions.getValidationValue(fileCategory, fileExtension, "header_signatures");
        if (!isBlank(headerSignatures) && !containsHeaderSignaturesProcessor(originalFile, headerSignatures)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid header_signatures")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Header signatures check passed, header signatures: ")
                .append(headerSignatures);
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.commonLogString, dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignaturesProcessor(), dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.isBlank(), dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.originalFile, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, and dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
containsHeaderSignaturesProcessor()
boolean dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignaturesProcessor (byte[] fileBytes, String headerSignaturesPattern) throws NumberFormatException private
Check if the file contains the expected header signatures
Parameters
fileBytes (byte[]) the file bytes of the file being validated
headerSignaturesPattern (String) the expected header signatures of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected header signatures, false otherwise
Definition at line 320 of file ValidationsHelper.java.
{
        if (isBlank(headerSignaturesPattern)) {
            return true;
        }
        String hexPattern = headerSignaturesPattern.replaceAll("\\p{Zs}", "");
        if (hexPattern.length() % 2 != 0) {
            hexPattern = "0" + hexPattern;
        }
        byte[] headerSignatures = new byte[hexPattern.length() / 2];
        for (int i = 0; i < hexPattern.length(); i += 2) {
            headerSignatures[i / 2] = (byte) Integer.parseInt(hexPattern.substring(i, i + 2), 16);
        }
        for (int i = 0; i < headerSignatures.length; i++) {
            if (i >= fileBytes.length || fileBytes[i] != headerSignatures[i]) {
                return false;
            }
        }
        return true;
    }
References dev.filechampion.filechampion4j.ValidationsHelper.isBlank().
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures().
containsMagicBytes()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes () private
Check if the file contains the expected magic bytes
Returns
StringBuilder (StringBuilder) the results of the magic bytes check
Definition at line 243 of file ValidationsHelper.java.
{
        String magicBytes = (String) extensions.getValidationValue(fileCategory, fileExtension, "magic_bytes");
        if (!isBlank(magicBytes) && !containsMagicBytesProcessor(originalFile, magicBytes)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid magic_bytes")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Magic bytes check passed, magic bytes: ")
                .append(magicBytes);
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.commonLogString, dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytesProcessor(), dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.isBlank(), dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.originalFile, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, and dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
containsMagicBytesProcessor()
boolean dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytesProcessor (byte[] originalFileBytes, String magicBytesPattern) throws NumberFormatException private
Check if the file contains the expected magic bytes
Parameters
originalFileBytes (byte[]) the file bytes of the file being validated
magicBytesPattern (String) the expected magic bytes of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected magic bytes, false otherwise
Definition at line 266 of file ValidationsHelper.java.
{
        if (originalFileBytes.length == 0 || magicBytesPattern == null || magicBytesPattern.isEmpty()) {
            return false;
        }
        magicBytesPattern = magicBytesPattern.replaceAll("\\p{Zs}", "");
        if (magicBytesPattern.length() % 2 != 0) {
            magicBytesPattern = "0" + magicBytesPattern;
        }
        byte[] magicBytes = new byte[magicBytesPattern.length() / 2];
        for (int i = 0; i < magicBytesPattern.length(); i += 2) {
            magicBytes[i / 2] = (byte) Integer.parseInt(magicBytesPattern.substring(i, i + 2), 16);
        }
        for (int i = 0; i < originalFileBytes.length - magicBytes.length; i++) {
            boolean found = true;
            for (int j = 0; j < magicBytes.length; j++) {
                if (originalFileBytes[i + j] != magicBytes[j]) {
                    found = false;
                    break;
                }
            }
            if (found) {
                return true;
            }
        }
        return false;
    }
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes().
deleteTempDir()
Boolean dev.filechampion.filechampion4j.ValidationsHelper.deleteTempDir (Path tempFilePath) private
Helper method to delete the temporary directory
Parameters
tempFilePath (Path) the path to the temporary file
Returns
Boolean (Boolean) true if the temporary directory was deleted successfully, false otherwise
Definition at line 417 of file ValidationsHelper.java.
{
        try (Stream<Path> walk = Files.walk(tempFilePath)) {
            walk.sorted(Comparator.reverseOrder())
            .map(Path::toFile)
            .forEach(File::delete);
            return true;
        } catch (Exception e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Delete temporary directoy failed: ").append(e.getMessage());
            logWarn(sharedStringBuilder);
            return false;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), and dev.filechampion.filechampion4j.ValidationsHelper.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType().
doValidations()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.doValidations () throws IOException, SecurityException, NumberFormatException private
Following initial validations and before plugins, this method is used to execute the validations for the file.
Returns
StringBuilder (StringBuilder) the results of the file validations
Exceptions
IOException (IOException) if the file cannot be saved/deleted to/from a temporary directory
SecurityException (SecurityException) if the accessed to file is denied for Files.probContentType
Definition at line 73 of file ValidationsHelper.java.
{
        checkFileSize();
        if (responseMsgCountFail > 0 && failFast) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        }
        checkMimeType();
        if (responseMsgCountFail > 0 && failFast) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        }
        containsMagicBytes();
        if (responseMsgCountFail > 0 && failFast) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        }
        containsHeaderSignatures();
        if (responseMsgCountFail > 0 && failFast) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        }
        containsFooterSignatures();
        if (responseMsgCountFail > 0 && failFast) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        }
        if (responseMsgCountFail > 0) {
            logWarn(sbresponseAggregationFail);
            return sbresponseAggregationFail;
        } else {
            logFine(sbresponseAggregationSuccess);
            return sbresponseAggregationSuccess;
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), dev.filechampion.filechampion4j.ValidationsHelper.failFast, dev.filechampion.filechampion4j.ValidationsHelper.logFine(), dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail, dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail, and dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults().
getFileExtension()
String dev.filechampion.filechampion4j.ValidationsHelper.getFileExtension (String fileName) private
Parse the file extension from the file name
Parameters
fileName (String) the name of the file being validated
Returns
String (String) the file extension of the file being validated
Definition at line 231 of file ValidationsHelper.java.
{
        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex == -1 || dotIndex == fileName.length() - 1) {
            return "";
        }
        return fileName.substring(dotIndex + 1);
    }
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults().
getValidationResults()
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults (String fileCategory, String fileName, byte[] originalFile, String mimeString) throws IOException, SecurityException, NumberFormatException
ValidationsHelper entry point for file validation
Parameters
fileCategory (String) the file category of the file being validated
fileName (String) the file name of the file being validated
originalFile (byte[]) the byte of the file being validated
mimeString (String) the mime type of the file being validated
Returns
StringBuilder (StringBuilder) the results of the file validations
Exceptions
IOException (IOException) if the file cannot be saved/deleted to/from a temporary directory
SecurityException (SecurityException) if the accessed to file is denied for Files.probContentType
Definition at line 51 of file ValidationsHelper.java.
{
        this.fileExtension = getFileExtension(fileName);
        this.responseMsgCountFail = 0;
        this.sbresponseAggregationFail = new StringBuilder();
        this.responseMsgCountSuccess = 0;
        this.sbresponseAggregationSuccess = new StringBuilder();
        this.fileCategory = fileCategory;
        this .failFast = extensions.getValidationValue(fileCategory, fileExtension, "fail_fast") != null ?
            (boolean) extensions.getValidationValue(fileCategory, fileExtension, "fail_fast") : false;
        this.originalFile = originalFile;
        this.mimeString = mimeString;
        this.commonLogString = " for file: " + fileName;
        return doValidations();
    }
References dev.filechampion.filechampion4j.ValidationsHelper.doValidations(), dev.filechampion.filechampion4j.ValidationsHelper.extensions, dev.filechampion.filechampion4j.ValidationsHelper.fileCategory, dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.ValidationsHelper.getFileExtension(), dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.ValidationsHelper.mimeString, and dev.filechampion.filechampion4j.ValidationsHelper.originalFile.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
isBlank()
boolean dev.filechampion.filechampion4j.ValidationsHelper.isBlank (String str) private
isBlank wrapper method for support of Java 8
Parameters
str (String) the string to check if empty or null
Returns
boolean (boolean) true if the string is empty or null, false otherwise
Definition at line 144 of file ValidationsHelper.java.
{
        return str == null || str.trim().isEmpty();
    }
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignaturesProcessor(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignaturesProcessor(), and dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes().
logFine()
void dev.filechampion.filechampion4j.ValidationsHelper.logFine (StringBuilder message) private
LOGGER.fine wrapper
Parameters
message (StringBuilder) - message to log
Definition at line 133 of file ValidationsHelper.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message.toString());
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.LOGGER.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
logWarn()
void dev.filechampion.filechampion4j.ValidationsHelper.logWarn (StringBuilder message) private
LOGGER.warning wrapper
Parameters
message (String) - message to log
Definition at line 123 of file ValidationsHelper.java.
{
        if (LOGGER.isLoggable(Level.WARNING)) {
            LOGGER.warning(message.toString());
        }
    }
References dev.filechampion.filechampion4j.ValidationsHelper.LOGGER.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), dev.filechampion.filechampion4j.ValidationsHelper.deleteTempDir(), dev.filechampion.filechampion4j.ValidationsHelper.doValidations(), and dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir().
saveFileToTempDir()
Path dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir (String fileExtension, byte[] originalFile) private
Helper method to save the file to a temporary directory
Parameters
fileExtension (String) the file extension of the file being validated
originalFile (byte[]) the file bytes of the file being validated
Returns
Path (Path) the path to the temporary file
Definition at line 397 of file ValidationsHelper.java.
{
        Path tempFilePath = null;
        try {
            // Create a temporary directory
            Path tempDir = Files.createTempDirectory("tempDir");
            tempFilePath = Files.createTempFile(tempDir, "tempFile", "." + fileExtension);
            Files.write(tempFilePath, originalFile);
        } catch (Exception e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Saving file to temporary directory failed: ").append(e.getMessage());
            logWarn(sharedStringBuilder);
            return null;
        }
        return tempFilePath;
    }
References dev.filechampion.filechampion4j.ValidationsHelper.fileExtension, dev.filechampion.filechampion4j.ValidationsHelper.logWarn(), dev.filechampion.filechampion4j.ValidationsHelper.originalFile, and dev.filechampion.filechampion4j.ValidationsHelper.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType().
Member Data Documentation
commonLogString
String dev.filechampion.filechampion4j.ValidationsHelper.commonLogString private
Definition at line 26 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), and dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes().
extensions
Extensions dev.filechampion.filechampion4j.ValidationsHelper.extensions private
Definition at line 19 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.ValidationsHelper(), dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults().
failFast
boolean dev.filechampion.filechampion4j.ValidationsHelper.failFast = false private
Definition at line 20 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
fileCategory
String dev.filechampion.filechampion4j.ValidationsHelper.fileCategory private
Definition at line 22 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults().
fileExtension
String dev.filechampion.filechampion4j.ValidationsHelper.fileExtension private
Definition at line 25 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults(), and dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir().
LOGGER
final Logger dev.filechampion.filechampion4j.ValidationsHelper.LOGGER = Logger.getLogger(ValidationsHelper.class.getName()) static private
Definition at line 18 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.logFine(), and dev.filechampion.filechampion4j.ValidationsHelper.logWarn().
mimeString
String dev.filechampion.filechampion4j.ValidationsHelper.mimeString private
Definition at line 24 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), and dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults().
originalFile
byte [] dev.filechampion.filechampion4j.ValidationsHelper.originalFile private
Definition at line 23 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults(), and dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir().
responseMsgCountFail
int dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountFail private
Definition at line 27 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
responseMsgCountSuccess
int dev.filechampion.filechampion4j.ValidationsHelper.responseMsgCountSuccess private
Definition at line 29 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), and dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes().
sbresponseAggregationFail
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationFail private
Definition at line 28 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
sbresponseAggregationSuccess
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.sbresponseAggregationSuccess private
Definition at line 30 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), and dev.filechampion.filechampion4j.ValidationsHelper.doValidations().
sharedStringBuilder
StringBuilder dev.filechampion.filechampion4j.ValidationsHelper.sharedStringBuilder = new StringBuilder() private
Definition at line 21 of file ValidationsHelper.java.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.deleteTempDir(), and dev.filechampion.filechampion4j.ValidationsHelper.saveFileToTempDir().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/ValidationsHelper.java