filechampion4j: dev.filechampion.filechampion4j.Extensions Class Reference
dev.filechampion.filechampion4j.Extensions Class Reference
Public Member Functions
Extensions (JSONObject jsonObject)
Object getValidationValue (String category, String extension, String validationKey)
Private Member Functions
void logInfo (String message)
void logWarn (String message)
void logFine (String message)
void mapConfiguredExtensions ()
void mapExtensionValidations ()
void setString (String validation, Object value)
void setBoolean (String validation, Object value)
void setArrayList (String validation, Object value)
void checkInputs (String category, String extension, String validationKey)
Private Attributes
StringBuilder sbLogMessage = new StringBuilder()
Map< String, Map< String, Object > > categoriesMap
Map< String, Map< String, Object > > extensionsMap
Map< String, Object > validationsMap
Map< String, Object > validationCache = new HashMap<>()
String sharedMessage1 = "Unsupported value type: "
String sharedMessage2 = " for key: "
List< String > allowedKeyValues
List< String > stringKeyValues
List< String > boolKeyValues = Arrays.asList("change_ownership", "name_encoding", "add_checksum", "fail_fast")
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(Extensions.class.getName())
Detailed Description
This class is used to load the Validations json objectand provide the validation values for a given extension.
Definition at line 16 of file Extensions.java.
Constructor & Destructor Documentation
Extensions()
dev.filechampion.filechampion4j.Extensions.Extensions (JSONObject jsonObject)
Constructor for Extensions class
Parameters
jsonObject (JSONObject) - The json object containing the validations
Exceptions
IllegalArgumentException if any of the json objects is invalid
Definition at line 55 of file Extensions.java.
{
        categoriesMap = new HashMap<>();
        extensionsMap = new HashMap<>();
        validationsMap = new HashMap<>();
        if (jsonObject == null) {
            throw new IllegalArgumentException("jsonObject cannot be null");
        }
        for (String category : jsonObject.keySet()) {
            categoriesMap.put(category, jsonObject.getJSONObject(category).toMap());
            sbLogMessage.replace(0, sbLogMessage.length(), category).append(" ")
                .append(jsonObject.getJSONObject(category).toString());
            logFine(sbLogMessage.toString());
        }
        if( categoriesMap.isEmpty()) {
            throw new IllegalArgumentException("Validations must contain categories objects");
        }
        mapConfiguredExtensions();
    }
References dev.filechampion.filechampion4j.Extensions.categoriesMap, dev.filechampion.filechampion4j.Extensions.extensionsMap, dev.filechampion.filechampion4j.Extensions.logFine(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, and dev.filechampion.filechampion4j.Extensions.validationsMap.
Member Function Documentation
checkInputs()
void dev.filechampion.filechampion4j.Extensions.checkInputs (String category, String extension, String validationKey) private
Checks input parameters of getValidationValue method
Parameters
category (String) - The category of the extension
extension (String) - The extension to get the validation value for
validationKey (String) - The validation key to get the value for
Definition at line 201 of file Extensions.java.
{
        if (!categoriesMap.containsKey(category)) {
            sbLogMessage.replace(0, sbLogMessage.length(), "category ").append(category)
                .append(" not found");
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
        if (!categoriesMap.get(category).containsKey(extension)) {
            sbLogMessage.replace(0, sbLogMessage.length(), "extension ").append(extension)
                .append(" not found");
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
        if (validationKey == null || validationKey.isEmpty()) {
            sbLogMessage.replace(0, sbLogMessage.length(), "validationKey cannot be null or empty");
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException("validationKey cannot be null or empty");
        }
    }
References dev.filechampion.filechampion4j.Extensions.categoriesMap, dev.filechampion.filechampion4j.Extensions.logWarn(), and dev.filechampion.filechampion4j.Extensions.sbLogMessage.
Referenced by dev.filechampion.filechampion4j.Extensions.getValidationValue().
getValidationValue()
Object dev.filechampion.filechampion4j.Extensions.getValidationValue (String category, String extension, String validationKey)
Returns the validation value for a given extension
Parameters
category (String) - The category of the extension
extension (String) - The file extension (without the dot)
validationKey (String) - The validation key
Returns
(Object) - The validation value or null if the validation key is not found/allowed
Exceptions
IllegalArgumentException if any of the parameters are invalid
Definition at line 229 of file Extensions.java.
{
        checkInputs(category, extension, validationKey);
        String cacheKey = category + "|" + extension + "|" + validationKey;
        if (validationCache.containsKey(cacheKey)) {
            sbLogMessage.replace(0, sbLogMessage.length(), "Returning ").append(validationKey)
                .append(" for ").append(extension).append(" (cached)");
            logFine(sbLogMessage.toString());
            return validationCache.get(cacheKey);
        }
        Object value = ((HashMap<?,?>) categoriesMap.get(category).get(extension)).get(validationKey);
        if (value != null) {
            validationCache.put(cacheKey, value);
            sbLogMessage.replace(0, sbLogMessage.length(), "Returning ").append(validationKey)
                .append(" for ").append(extension);
            logFine(sbLogMessage.toString());
            return value;
        } else {
            sbLogMessage.replace(0, sbLogMessage.length(), "Returning null for ")
                .append(validationKey).append(" for ").append(extension);
            logFine(sbLogMessage.toString());
            return null;
        }
    }
References dev.filechampion.filechampion4j.Extensions.categoriesMap, dev.filechampion.filechampion4j.Extensions.checkInputs(), dev.filechampion.filechampion4j.Extensions.logFine(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, and dev.filechampion.filechampion4j.Extensions.validationCache.
Referenced by dev.filechampion.filechampion4j.ValidationsHelper.checkFileSize(), dev.filechampion.filechampion4j.ValidationsHelper.checkMimeType(), dev.filechampion.filechampion4j.ValidationsHelper.containsFooterSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsHeaderSignatures(), dev.filechampion.filechampion4j.ValidationsHelper.containsMagicBytes(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeAfterPluginsProcess(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.ValidationsHelper.getValidationResults(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
logFine()
void dev.filechampion.filechampion4j.Extensions.logFine (String message) private
Definition at line 28 of file Extensions.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message);
        }
    }
References dev.filechampion.filechampion4j.Extensions.LOGGER.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions(), dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), and dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
logInfo()
void dev.filechampion.filechampion4j.Extensions.logInfo (String message) private
Definition at line 18 of file Extensions.java.
{
        if (LOGGER.isLoggable(Level.INFO)) {
            LOGGER.info(message);
        }
    }
References dev.filechampion.filechampion4j.Extensions.LOGGER.
Referenced by dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
logWarn()
void dev.filechampion.filechampion4j.Extensions.logWarn (String message) private
Definition at line 23 of file Extensions.java.
{
        if (LOGGER.isLoggable(Level.WARNING)) {
            LOGGER.warning(message);
        }
    }
References dev.filechampion.filechampion4j.Extensions.LOGGER.
Referenced by dev.filechampion.filechampion4j.Extensions.checkInputs(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), and dev.filechampion.filechampion4j.Extensions.setString().
mapConfiguredExtensions()
void dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions () private
Load extensions from json object into extensionsMap
Definition at line 80 of file Extensions.java.
{
        for (Map.Entry<String, Object> extensionEntry : categoriesMap.entrySet().iterator().next().getValue().entrySet()) {
            String extension = extensionEntry.getKey();
            if (extensionEntry.getValue() instanceof HashMap) {
                extensionsMap.put(extensionEntry.getKey(), (HashMap) extensionEntry.getValue());
                sbLogMessage.replace(0, sbLogMessage.length(), extension).append(" ")
                    .append(extensionEntry.getValue().toString());
                logFine(sbLogMessage.toString());
            } else {
                sbLogMessage.replace(0, sbLogMessage.length(), sharedMessage1)
                    .append(extensionEntry.getValue().getClass().getName())
                    .append(sharedMessage2)
                    .append(extension);
                logWarn(sbLogMessage.toString());
                throw new IllegalArgumentException(sbLogMessage.toString());
            }
        }
        if (extensionsMap.entrySet().iterator().next().getValue().entrySet().isEmpty()) {
            sbLogMessage.replace(0, sbLogMessage.length(), "At least one validation must be configured");
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
        mapExtensionValidations();
    }
References dev.filechampion.filechampion4j.Extensions.categoriesMap, dev.filechampion.filechampion4j.Extensions.extensionsMap, dev.filechampion.filechampion4j.Extensions.logFine(), dev.filechampion.filechampion4j.Extensions.logWarn(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, dev.filechampion.filechampion4j.Extensions.sharedMessage1, and dev.filechampion.filechampion4j.Extensions.sharedMessage2.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions().
mapExtensionValidations()
void dev.filechampion.filechampion4j.Extensions.mapExtensionValidations () private
Load extension validations into validationsMap
Definition at line 108 of file Extensions.java.
{
        for (Map.Entry<String, Object> validationEntry : extensionsMap.entrySet().iterator().next().getValue().entrySet() ) {
            String validation = validationEntry.getKey();
            Object value = validationEntry.getValue();
            if (allowedKeyValues.contains(validation)) {
                if (value instanceof String || value instanceof Integer) {
                    setString(validation, value);
                } else if (value instanceof Boolean) {
                    setBoolean(validation, value);
                } else if (value instanceof ArrayList ) {
                    setArrayList(validation, value);
                } else {
                    sbLogMessage.replace(0, sbLogMessage.length(),  sharedMessage1)
                            .append(value.getClass().getName())
                            .append(sharedMessage2)
                            .append(validation);
                    throw new IllegalArgumentException(sbLogMessage.toString());
                }
            } else {
                sbLogMessage.replace(0, sbLogMessage.length(), "Unsupported key: ")
                .append(validation);
                logWarn(sbLogMessage.toString());
                throw new IllegalArgumentException(sbLogMessage.toString());
            }
        }
        sbLogMessage.replace(0, sbLogMessage.length(), "Loaded ").append(categoriesMap.size()).append(" categories, ")
            .append(extensionsMap.size()).append(" extensions, ")
            .append(validationsMap.size()).append(" validations");
        logFine(sbLogMessage.toString());
        logInfo("Loaded Validations Configurtion");
    }
References dev.filechampion.filechampion4j.Extensions.allowedKeyValues, dev.filechampion.filechampion4j.Extensions.categoriesMap, dev.filechampion.filechampion4j.Extensions.extensionsMap, dev.filechampion.filechampion4j.Extensions.logFine(), dev.filechampion.filechampion4j.Extensions.logInfo(), dev.filechampion.filechampion4j.Extensions.logWarn(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), dev.filechampion.filechampion4j.Extensions.setString(), dev.filechampion.filechampion4j.Extensions.sharedMessage1, dev.filechampion.filechampion4j.Extensions.sharedMessage2, and dev.filechampion.filechampion4j.Extensions.validationsMap.
Referenced by dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions().
setArrayList()
void dev.filechampion.filechampion4j.Extensions.setArrayList (String validation, Object value) private
Sets the value of ArrayList validation key
Parameters
validation (String) - The validation key
value (Object) - The value of the validation key
Definition at line 182 of file Extensions.java.
{
        if (validation.equals("extension_plugins")) {
            validationsMap.put(validation, (ArrayList) value);
        } else {
            sbLogMessage.replace(0, sbLogMessage.length(),  sharedMessage1)
                .append(value.getClass().getName())
                .append(sharedMessage2)
                .append(validation);
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
    }
References dev.filechampion.filechampion4j.Extensions.logWarn(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, dev.filechampion.filechampion4j.Extensions.sharedMessage1, dev.filechampion.filechampion4j.Extensions.sharedMessage2, and dev.filechampion.filechampion4j.Extensions.validationsMap.
Referenced by dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
setBoolean()
void dev.filechampion.filechampion4j.Extensions.setBoolean (String validation, Object value) private
Sets the value of Boolean validation key
Parameters
validation (String) - The validation key
value (Object) - The value of the validation key
Definition at line 164 of file Extensions.java.
{
        if (boolKeyValues.contains(validation)) {
            validationsMap.put(validation, (boolean) value);
        } else {
            sbLogMessage.replace(0, sbLogMessage.length(),  sharedMessage1)
                .append(value.getClass().getName())
                .append(sharedMessage2)
                .append(validation);
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
    }
References dev.filechampion.filechampion4j.Extensions.boolKeyValues, dev.filechampion.filechampion4j.Extensions.logWarn(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, dev.filechampion.filechampion4j.Extensions.sharedMessage1, dev.filechampion.filechampion4j.Extensions.sharedMessage2, and dev.filechampion.filechampion4j.Extensions.validationsMap.
Referenced by dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
setString()
void dev.filechampion.filechampion4j.Extensions.setString (String validation, Object value) private
Sets the value of String validation key
Parameters
validation (String) - The validation key
value (Object) - The value of the validation key
Definition at line 146 of file Extensions.java.
{
        if (stringKeyValues.contains(validation)) {
            validationsMap.put(validation, value.toString());
        } else {
            sbLogMessage.replace(0, sbLogMessage.length(),  sharedMessage1)
                .append(value.getClass().getName())
                .append(sharedMessage2)
                .append(validation);
            logWarn(sbLogMessage.toString());
            throw new IllegalArgumentException(sbLogMessage.toString());
        }
    }
References dev.filechampion.filechampion4j.Extensions.logWarn(), dev.filechampion.filechampion4j.Extensions.sbLogMessage, dev.filechampion.filechampion4j.Extensions.sharedMessage1, dev.filechampion.filechampion4j.Extensions.sharedMessage2, dev.filechampion.filechampion4j.Extensions.stringKeyValues, and dev.filechampion.filechampion4j.Extensions.validationsMap.
Referenced by dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
Member Data Documentation
allowedKeyValues
List<String> dev.filechampion.filechampion4j.Extensions.allowedKeyValues private
Initial value:
= Arrays.asList("mime_type", "magic_bytes", "header_signatures",
        "footer_signatures", "change_ownership", "change_ownership_user", "change_ownership_mode",
        "name_encoding", "max_size", "extension_plugins", "add_checksum", "fail_fast")
Definition at line 42 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
boolKeyValues
List<String> dev.filechampion.filechampion4j.Extensions.boolKeyValues = Arrays.asList("change_ownership", "name_encoding", "add_checksum", "fail_fast") private
Definition at line 48 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.setBoolean().
categoriesMap
Map<String, Map<String, Object> > dev.filechampion.filechampion4j.Extensions.categoriesMap private
Definition at line 35 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions(), dev.filechampion.filechampion4j.Extensions.checkInputs(), dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), and dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
extensionsMap
Map<String, Map<String, Object> > dev.filechampion.filechampion4j.Extensions.extensionsMap private
Definition at line 36 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), and dev.filechampion.filechampion4j.Extensions.mapExtensionValidations().
LOGGER
final Logger dev.filechampion.filechampion4j.Extensions.LOGGER = Logger.getLogger(Extensions.class.getName()) static private
Definition at line 17 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.logFine(), dev.filechampion.filechampion4j.Extensions.logInfo(), and dev.filechampion.filechampion4j.Extensions.logWarn().
sbLogMessage
StringBuilder dev.filechampion.filechampion4j.Extensions.sbLogMessage = new StringBuilder() private
Definition at line 34 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions(), dev.filechampion.filechampion4j.Extensions.checkInputs(), dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), and dev.filechampion.filechampion4j.Extensions.setString().
sharedMessage1
String dev.filechampion.filechampion4j.Extensions.sharedMessage1 = "Unsupported value type: " private
Definition at line 39 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), and dev.filechampion.filechampion4j.Extensions.setString().
sharedMessage2
String dev.filechampion.filechampion4j.Extensions.sharedMessage2 = " for key: " private
Definition at line 40 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.mapConfiguredExtensions(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), and dev.filechampion.filechampion4j.Extensions.setString().
stringKeyValues
List<String> dev.filechampion.filechampion4j.Extensions.stringKeyValues private
Initial value:
= Arrays.asList("mime_type", "magic_bytes", "header_signatures",
    "footer_signatures", "change_ownership_user", "change_ownership_mode",
    "max_size", "extension_plugins")
Definition at line 45 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.setString().
validationCache
Map<String, Object> dev.filechampion.filechampion4j.Extensions.validationCache = new HashMap<>() private
Definition at line 38 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.getValidationValue().
validationsMap
Map<String, Object> dev.filechampion.filechampion4j.Extensions.validationsMap private
Definition at line 37 of file Extensions.java.
Referenced by dev.filechampion.filechampion4j.Extensions.Extensions(), dev.filechampion.filechampion4j.Extensions.mapExtensionValidations(), dev.filechampion.filechampion4j.Extensions.setArrayList(), dev.filechampion.filechampion4j.Extensions.setBoolean(), and dev.filechampion.filechampion4j.Extensions.setString().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/Extensions.java