filechampion4j: dev.filechampion.filechampion4j.Extension Class Reference
dev.filechampion.filechampion4j.Extension Class Reference
Public Member Functions
Extension (String fileCategory, String fileExtension, JSONObject configJsonObject)
JSONArray getExtensionPlugins ()
String getMimeType ()
String getMagicBytes ()
String getHeaderSignatures ()
String getFooterSignatures ()
JSONArray getAntivirusScanJson ()
boolean isChangeOwnership ()
String getChangeOwnershipUser ()
String getChangeOwnershipMode ()
boolean isNameEncoding ()
int getMaxSize ()
Private Member Functions
void setValuesFromJson (JSONObject configJsonObject)
Private Attributes
String mimeType
String magicBytes
String headerSignatures
String footerSignatures
JSONArray antivirusScanJson
boolean changeOwnership
String changeOwnershipUser
String changeOwnershipMode
boolean nameEncoding
int maxSize
String fileCategory
String fileExtension
JSONArray extensionPlugins
Detailed Description
This class is used to fetch the Json configuration data for a single file extension. The Json configuration data is then used to create an Extension object.
Definition at line 11 of file Extension.java.
Constructor & Destructor Documentation
Extension()
dev.filechampion.filechampion4j.Extension.Extension (String fileCategory, String fileExtension, JSONObject configJsonObject)
Constructor
Parameters
fileCategory (String) the file category (e.g. "Documents")
fileExtension (String) the file extension (e.g. "pdf")
configJsonObject (JSONObject) the Json configuration data
Returns
(Extension) an Extension object
Exceptions
IllegalArgumentException (IllegalArgumentException) if the file category or file extension is not found in the Json configuration data
Definition at line 35 of file Extension.java.
{
        if (fileCategory == null || fileCategory.trim().isEmpty()) {
            String excMsg = String.format("Invalid argument(s) provided: fileCategory=%s, fileExtension=%s, json=%s",
              fileCategory, fileExtension, configJsonObject);
            throw new IllegalArgumentException(excMsg);
        }
        this.fileCategory = fileCategory;
        this.fileExtension = fileExtension;
        setValuesFromJson(configJsonObject);
    }
References dev.filechampion.filechampion4j.Extension.fileCategory, dev.filechampion.filechampion4j.Extension.fileExtension, and dev.filechampion.filechampion4j.Extension.setValuesFromJson().
Member Function Documentation
getAntivirusScanJson()
JSONArray dev.filechampion.filechampion4j.Extension.getAntivirusScanJson ()
Definition at line 66 of file Extension.java.
{
        return antivirusScanJson;
    }
References dev.filechampion.filechampion4j.Extension.antivirusScanJson.
getChangeOwnershipMode()
String dev.filechampion.filechampion4j.Extension.getChangeOwnershipMode ()
Definition at line 78 of file Extension.java.
{
        return changeOwnershipMode;
    }
References dev.filechampion.filechampion4j.Extension.changeOwnershipMode.
Referenced by dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir().
getChangeOwnershipUser()
String dev.filechampion.filechampion4j.Extension.getChangeOwnershipUser ()
Definition at line 74 of file Extension.java.
{
        return changeOwnershipUser;
    }
References dev.filechampion.filechampion4j.Extension.changeOwnershipUser.
Referenced by dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir().
getExtensionPlugins()
JSONArray dev.filechampion.filechampion4j.Extension.getExtensionPlugins ()
Definition at line 46 of file Extension.java.
{
        return extensionPlugins;
    }
References dev.filechampion.filechampion4j.Extension.extensionPlugins.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), and dev.filechampion.filechampion4j.FileValidator.validateFile().
getFooterSignatures()
String dev.filechampion.filechampion4j.Extension.getFooterSignatures ()
Definition at line 62 of file Extension.java.
{
        return footerSignatures;
    }
References dev.filechampion.filechampion4j.Extension.footerSignatures.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
getHeaderSignatures()
String dev.filechampion.filechampion4j.Extension.getHeaderSignatures ()
Definition at line 58 of file Extension.java.
{
        return headerSignatures;
    }
References dev.filechampion.filechampion4j.Extension.headerSignatures.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
getMagicBytes()
String dev.filechampion.filechampion4j.Extension.getMagicBytes ()
Definition at line 54 of file Extension.java.
{
        return magicBytes;
    }
References dev.filechampion.filechampion4j.Extension.magicBytes.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
getMaxSize()
int dev.filechampion.filechampion4j.Extension.getMaxSize ()
Definition at line 86 of file Extension.java.
{
        return maxSize;
    }
References dev.filechampion.filechampion4j.Extension.maxSize.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
getMimeType()
String dev.filechampion.filechampion4j.Extension.getMimeType ()
Definition at line 50 of file Extension.java.
{
        return mimeType;
    }
References dev.filechampion.filechampion4j.Extension.mimeType.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
isChangeOwnership()
boolean dev.filechampion.filechampion4j.Extension.isChangeOwnership ()
Definition at line 70 of file Extension.java.
{
        return changeOwnership;
    }
References dev.filechampion.filechampion4j.Extension.changeOwnership.
isNameEncoding()
boolean dev.filechampion.filechampion4j.Extension.isNameEncoding ()
Definition at line 82 of file Extension.java.
{
        return nameEncoding;
    }
References dev.filechampion.filechampion4j.Extension.nameEncoding.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
setValuesFromJson()
void dev.filechampion.filechampion4j.Extension.setValuesFromJson (JSONObject configJsonObject) private
This method is used to set the values of the Extension object from the Json configuration data.
Parameters
configJsonObject (JSONObject) the Json configuration data
Exceptions
IllegalArgumentException if the file category or file extension is not found in the Json configuration data
Definition at line 95 of file Extension.java.
{
        if (!configJsonObject.has(fileCategory)) {
            throw new IllegalArgumentException("Category not found in JSON: " + fileCategory);
        }
        JSONObject categoryJson = configJsonObject.optJSONObject(fileCategory);
        if (!categoryJson.has(fileExtension)) {
            throw new IllegalArgumentException("Extension not found in JSON: " + fileExtension);
        }
        JSONObject extensionJson = categoryJson.optJSONObject(fileExtension);
        this.extensionPlugins = extensionJson.optJSONArray("extension_plugins");
        this.mimeType = extensionJson.optString("mime_type");
        this.magicBytes = extensionJson.optString("magic_bytes");
        this.headerSignatures = extensionJson.optString("header_signatures");
        this.footerSignatures = extensionJson.optString("footer_signatures");
        this.antivirusScanJson = extensionJson.optJSONArray("antivirus_scan");
        this.changeOwnership = extensionJson.optBoolean("change_ownership");
        this.changeOwnershipUser = extensionJson.optString("change_ownership_user");
        this.changeOwnershipMode = extensionJson.optString("change_ownership_mode");
        this.nameEncoding = extensionJson.optBoolean("name_encoding");
        this.maxSize = extensionJson.optInt("max_size");
    }
References dev.filechampion.filechampion4j.Extension.fileCategory, and dev.filechampion.filechampion4j.Extension.fileExtension.
Referenced by dev.filechampion.filechampion4j.Extension.Extension().
Member Data Documentation
antivirusScanJson
JSONArray dev.filechampion.filechampion4j.Extension.antivirusScanJson private
Definition at line 16 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getAntivirusScanJson().
changeOwnership
boolean dev.filechampion.filechampion4j.Extension.changeOwnership private
Definition at line 17 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.isChangeOwnership().
changeOwnershipMode
String dev.filechampion.filechampion4j.Extension.changeOwnershipMode private
Definition at line 19 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getChangeOwnershipMode().
changeOwnershipUser
String dev.filechampion.filechampion4j.Extension.changeOwnershipUser private
Definition at line 18 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getChangeOwnershipUser().
extensionPlugins
JSONArray dev.filechampion.filechampion4j.Extension.extensionPlugins private
Definition at line 24 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getExtensionPlugins().
fileCategory
String dev.filechampion.filechampion4j.Extension.fileCategory private
Definition at line 22 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.Extension(), and dev.filechampion.filechampion4j.Extension.setValuesFromJson().
fileExtension
String dev.filechampion.filechampion4j.Extension.fileExtension private
Definition at line 23 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.Extension(), and dev.filechampion.filechampion4j.Extension.setValuesFromJson().
footerSignatures
String dev.filechampion.filechampion4j.Extension.footerSignatures private
Definition at line 15 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getFooterSignatures().
headerSignatures
String dev.filechampion.filechampion4j.Extension.headerSignatures private
Definition at line 14 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getHeaderSignatures().
magicBytes
String dev.filechampion.filechampion4j.Extension.magicBytes private
Definition at line 13 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getMagicBytes().
maxSize
int dev.filechampion.filechampion4j.Extension.maxSize private
Definition at line 21 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getMaxSize().
mimeType
String dev.filechampion.filechampion4j.Extension.mimeType private
Definition at line 12 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.getMimeType().
nameEncoding
boolean dev.filechampion.filechampion4j.Extension.nameEncoding private
Definition at line 20 of file Extension.java.
Referenced by dev.filechampion.filechampion4j.Extension.isNameEncoding().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/Extension.java