filechampion4j: dev.filechampion.filechampion4j.IndexSynchronizer Class Reference
dev.filechampion.filechampion4j.IndexSynchronizer Class Reference
Public Member Functions
IndexSynchronizer ()
void addItem (char[] item, String secret)
char[] getSecretValue (String secret)
void checkAndRemoveStaleSecrets (long maxAgeMillis)
Private Member Functions
void updateListIndex (int removedIndex)
void logFine (StringBuilder message)
Private Attributes
List< char[]> credList
Map< String, Map< Integer, Long > > listIndex
ReadWriteLock lock
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(IndexSynchronizer.class.getName())
Detailed Description
Synchronizes and stores the name, index, and timesamp of credentials in the cache.
Definition at line 12 of file IndexSynchronizer.java.
Constructor & Destructor Documentation
IndexSynchronizer()
dev.filechampion.filechampion4j.IndexSynchronizer.IndexSynchronizer ()
IndexSynchronizer constructor.
Definition at line 21 of file IndexSynchronizer.java.
{
        credList = new ArrayList<>();
        listIndex = new ConcurrentHashMap<>();
        lock = new ReentrantReadWriteLock();
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.credList, dev.filechampion.filechampion4j.IndexSynchronizer.listIndex, and dev.filechampion.filechampion4j.IndexSynchronizer.lock.
Member Function Documentation
addItem()
void dev.filechampion.filechampion4j.IndexSynchronizer.addItem (char[] item, String secret)
Adds a new secret to the cache.
Parameters
item (char[]) secret value as char array for mutability.
secret (String) name of the secret.
Definition at line 32 of file IndexSynchronizer.java.
{
        lock.writeLock().lock();
        try {
            credList.add(item);
            Map<Integer, Long> secretEntry = new ConcurrentHashMap<>();
            secretEntry.put(credList.size() - 1, System.currentTimeMillis());
            listIndex.put(secret, secretEntry);
        } finally {
            lock.writeLock().unlock();
        }
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.credList, dev.filechampion.filechampion4j.IndexSynchronizer.listIndex, and dev.filechampion.filechampion4j.IndexSynchronizer.lock.
checkAndRemoveStaleSecrets()
void dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets (long maxAgeMillis)
Remove secrets that have not been accessed in the last maxAgeMillis milliseconds, and synchronize the cache.
Parameters
maxAgeMillis (long) maximum age of a secret in milliseconds.
Definition at line 69 of file IndexSynchronizer.java.
{
        lock.writeLock().lock();
        try {
            long currentTime = System.currentTimeMillis();
            Iterator<Map.Entry<String, Map<Integer, Long>>> iterator = listIndex.entrySet().iterator();
            while (iterator.hasNext()) {
                Map.Entry<String, Map<Integer, Long>> entry = iterator.next();
                Map<Integer, Long> secretEntry = entry.getValue();
                long timestamp = secretEntry.values().iterator().next();
                if (currentTime - timestamp > maxAgeMillis) {
                    int index = secretEntry.keySet().iterator().next();
                    Arrays.fill(credList.get(index), '\u0000');
                    credList.remove(index);
                    iterator.remove();
                    updateListIndex(index);
                    logFine(new StringBuilder("Removed stale secret: ").append(entry.getKey()));
                }
            }
        } finally {
            lock.writeLock().unlock();
        }
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.credList, dev.filechampion.filechampion4j.IndexSynchronizer.listIndex, dev.filechampion.filechampion4j.IndexSynchronizer.lock, dev.filechampion.filechampion4j.IndexSynchronizer.logFine(), and dev.filechampion.filechampion4j.IndexSynchronizer.updateListIndex().
getSecretValue()
char[] dev.filechampion.filechampion4j.IndexSynchronizer.getSecretValue (String secret)
Get a secret value from the cache.
Parameters
secret (String) name of the secret.
Returns
(char[]) secret value as char array for mutability, or null if not found.
Definition at line 49 of file IndexSynchronizer.java.
{
        lock.readLock().lock();
        try {
            Map<Integer, Long> secretEntry = listIndex.get(secret);
            if (secretEntry != null) {
                int index = secretEntry.keySet().iterator().next();
                secretEntry.put(index, System.currentTimeMillis());
                logFine(new StringBuilder("Retrieved secret: ").append(secret));
                return credList.get(index);
            }
            return null;
        } finally {
            lock.readLock().unlock();
        }
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.credList, dev.filechampion.filechampion4j.IndexSynchronizer.listIndex, dev.filechampion.filechampion4j.IndexSynchronizer.lock, and dev.filechampion.filechampion4j.IndexSynchronizer.logFine().
logFine()
void dev.filechampion.filechampion4j.IndexSynchronizer.logFine (StringBuilder message) private
LOGGER.fine wrapper
Parameters
message (StringBuilder) - message to log
Definition at line 114 of file IndexSynchronizer.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message.toString());
        }
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.LOGGER.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets(), and dev.filechampion.filechampion4j.IndexSynchronizer.getSecretValue().
updateListIndex()
void dev.filechampion.filechampion4j.IndexSynchronizer.updateListIndex (int removedIndex) private
Update the index of all secrets in the cache after a secret has been removed.
Parameters
removedIndex (int) index of the removed secret.
Definition at line 96 of file IndexSynchronizer.java.
{
        for (Map.Entry<String, Map<Integer, Long>> entry : listIndex.entrySet()) {
            Map<Integer, Long> secretEntry = entry.getValue();
            int currentIndex = secretEntry.keySet().iterator().next();
            if (currentIndex > removedIndex) {
                secretEntry.put(currentIndex - 1, secretEntry.remove(currentIndex));
            }
        }
    }
References dev.filechampion.filechampion4j.IndexSynchronizer.listIndex.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets().
Member Data Documentation
credList
List<char[]> dev.filechampion.filechampion4j.IndexSynchronizer.credList private
Definition at line 13 of file IndexSynchronizer.java.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.IndexSynchronizer(), dev.filechampion.filechampion4j.IndexSynchronizer.addItem(), dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets(), and dev.filechampion.filechampion4j.IndexSynchronizer.getSecretValue().
listIndex
Map<String, Map<Integer, Long> > dev.filechampion.filechampion4j.IndexSynchronizer.listIndex private
Definition at line 14 of file IndexSynchronizer.java.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.IndexSynchronizer(), dev.filechampion.filechampion4j.IndexSynchronizer.addItem(), dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets(), dev.filechampion.filechampion4j.IndexSynchronizer.getSecretValue(), and dev.filechampion.filechampion4j.IndexSynchronizer.updateListIndex().
lock
ReadWriteLock dev.filechampion.filechampion4j.IndexSynchronizer.lock private
Definition at line 15 of file IndexSynchronizer.java.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.IndexSynchronizer(), dev.filechampion.filechampion4j.IndexSynchronizer.addItem(), dev.filechampion.filechampion4j.IndexSynchronizer.checkAndRemoveStaleSecrets(), and dev.filechampion.filechampion4j.IndexSynchronizer.getSecretValue().
LOGGER
final Logger dev.filechampion.filechampion4j.IndexSynchronizer.LOGGER = Logger.getLogger(IndexSynchronizer.class.getName()) static private
Definition at line 16 of file IndexSynchronizer.java.
Referenced by dev.filechampion.filechampion4j.IndexSynchronizer.logFine().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/IndexSynchronizer.java