filechampion4j: dev.filechampion.filechampion4j.FileValidator Class Reference
dev.filechampion.filechampion4j.FileValidator Class Reference
Public Member Functions
FileValidator (JSONObject configJsonObject) throws IllegalArgumentException
ValidationResponse validateFile (String fileCategory, byte[] originalFile, String fileName, Path outputDir, String mimeString)
ValidationResponse validateFile (String fileCategory, Path filePath, String fileName, Path outputDir, String mimeString)
ValidationResponse validateFile (String fileCategory, byte[] originalFile, String fileName, String mimeString)
ValidationResponse validateFile (String fileCategory, byte[] originalFile, String fileName, Path outputDir)
ValidationResponse validateFile (String fileCategory, Path filePath, String fileName, String mimeString)
ValidationResponse validateFile (String fileCategory, Path filePath, String fileName, Path outputDir)
ValidationResponse validateFile (String fileCategory, byte[] originalFile, String fileName)
ValidationResponse validateFile (String fileCategory, Path filePath, String fileName)
Private Member Functions
ValidationResponse validateFileMain ()
ValidationResponse doValidations (String originalFilenameClean)
void logInfo (StringBuilder message)
void logWarn (StringBuilder message)
void logSevere (StringBuilder message)
void logFine (StringBuilder message)
void loadPlugins ()
void checkPluginsConfig ()
void checkPluginsExist (JSONObject validationsJsonObject, String categroyKey, String extensionKey)
void checkMethodInputs (String fileCategory, byte[] originalFile, String fileName)
String executeBeforePlugins (String fileCategory, String fileExtension)
String executeAfterPlugins (String fileCategory, String fileExtension)
String executePlugin (String extensionPlugin, Map< String, StepConfig > stepConfigs, String fileExtension)
boolean isBlank (String str)
Boolean checkFileSize (int originalFileSize, int extensionMaxSize)
Path saveFileToTempDir (String fileExtension, byte[] originalFile)
Boolean deleteTempDir (Path tempFilePath)
boolean checkMimeType (byte[] originalFileBytes, String fileExtension, String mimeType)
String getFileExtension (String fileName)
boolean containsMagicBytes (byte[] originalFileBytes, String magicBytesPattern)
boolean containsHeaderSignatures (byte[] fileBytes, String headerSignaturesPattern)
boolean containsFooterSignatures (byte[] fileBytes, String footerSignaturesPattern)
String calculateChecksum (byte[] fileBytes)
String saveFileToOutputDir (String fileCategory, String fileExtension, Path outDir, String fileName, byte[] fileBytes)
String setFileAttributes (Path targetFilePath, String changeOwnershipUser, String changePermissionsMode)
Private Attributes
JSONObject configJsonObject
PluginsHelper pluginsHelper
Map< String, StepConfig > stepConfigsBefore = new HashMap<>()
Map< String, StepConfig > stepConfigsAfter = new HashMap<>()
Extensions extensions
StringBuilder sharedStringBuilder = new StringBuilder()
String sharedStepMessage = "Step: "
String errorResponse = "File is not valid."
String fileCategory
String fileName
byte[] originalFile
String mimeString
Path outDir
String fileExtension
String commonFileError = "Error reading file: "
String commonLogString
int responseMsgCountFail
StringBuilder sbresponseAggregationFail
int responseMsgCountSuccess
StringBuilder sbresponseAggregationSuccess
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(FileValidator.class.getName())
Detailed Description
This class is used to validate files
Author
filechampion
Version
0.9.8.2
See also
FileChampion4j Wiki
Definition at line 28 of file FileValidator.java.
Constructor & Destructor Documentation
FileValidator()
dev.filechampion.filechampion4j.FileValidator.FileValidator (JSONObject configJsonObject) throws IllegalArgumentException
This method is used to initiate the class with relevant json configurations
Parameters
configJsonObject
Definition at line 68 of file FileValidator.java.
{
        if (configJsonObject == null || configJsonObject.isEmpty() || !configJsonObject.has("Validations")) {
            throw new IllegalArgumentException("Config JSON object cannot be null or empty, and must have Validations section.");
        } else {
            try {
                extensions = new Extensions(configJsonObject.getJSONObject("Validations"));
            } catch (Exception e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error initializing extensions: ")
                    .append(e.getMessage());
                logWarn(sharedStringBuilder);
                throw new IllegalArgumentException("Error initializing extensions: " + e.getMessage());
            }
        }
        this.configJsonObject = configJsonObject;
        if (configJsonObject.has("Plugins")) {
            try {
                pluginsHelper = new PluginsHelper(configJsonObject.getJSONObject("Plugins"));
                loadPlugins();
                checkPluginsConfig();
            } catch (Exception e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error initializing plugins: ")
                    .append(e.getMessage());
                logWarn(sharedStringBuilder);
                throw new IllegalArgumentException("Error initializing plugins: " + e.getMessage());
            }
        }
    }
References dev.filechampion.filechampion4j.FileValidator.checkPluginsConfig(), dev.filechampion.filechampion4j.FileValidator.configJsonObject, dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.loadPlugins(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.pluginsHelper, and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Member Function Documentation
calculateChecksum()
String dev.filechampion.filechampion4j.FileValidator.calculateChecksum (byte[] fileBytes) private
Calculate the checksum of the file
Parameters
fileBytes (byte[]) the file bytes of the file being validated
Returns
String (String) the SHA-256 checksum of the file
Definition at line 993 of file FileValidator.java.
{
        try {
            SH256Calculate paralChecksum = new SH256Calculate(fileBytes);
            byte[] checksum = paralChecksum.getChecksum();
            return new BigInteger(1, checksum).toString(16);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
References dev.filechampion.filechampion4j.SH256Calculate.getChecksum().
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
checkFileSize()
Boolean dev.filechampion.filechampion4j.FileValidator.checkFileSize (int originalFileSize, int extensionMaxSize) private
Compare file size to the maximum allowed size
Parameters
originalFileSize (int) the size of the file being validated
extensionMaxSize (int) the maximum allowed size of the file being validated
Returns
Boolean (Boolean) true if the file size is less than or equal to the maximum allowed size, false otherwise
Definition at line 815 of file FileValidator.java.
{
        return (extensionMaxSize == 0) || (originalFileSize / 1000) <= extensionMaxSize;
    }
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
checkMethodInputs()
void dev.filechampion.filechampion4j.FileValidator.checkMethodInputs (String fileCategory, byte[] originalFile, String fileName) private
This method is used to check that method inputs are not null or empty
Parameters
fileCategory (String) the file category of the file being validated
originalFile (byte[]) the file being validated
fileName (String) the file name of the file being validated
Definition at line 618 of file FileValidator.java.
{
        if (isBlank(fileCategory)) {
            throw new IllegalArgumentException("fileCategory cannot be null or empty.");
        }
        if (isBlank(fileName)) {
            throw new IllegalArgumentException("fileName cannot be null or empty.");
        }
        if (originalFile == null || originalFile.length == 0) {
            throw new IllegalArgumentException("originalFile cannot be null or empty.");
        }
        this.originalFile = originalFile;
    }
References dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.isBlank(), and dev.filechampion.filechampion4j.FileValidator.originalFile.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFileMain().
checkMimeType()
boolean dev.filechampion.filechampion4j.FileValidator.checkMimeType (byte[] originalFileBytes, String fileExtension, String mimeType) private
Compare the file MIME type to the expected MIME type
Parameters
originalFileBytes (byte[]) the file bytes of the file being validated
fileExtension (String) the file extension of the file being validated
mimeType (String) the expected MIME type of the file being validated
Returns
Boolean (Boolean) true if the file MIME type matches the expected MIME type, false otherwise
Definition at line 865 of file FileValidator.java.
{
        String fileMimeType = isBlank(mimeString) ? "" : mimeString;
        if (isBlank(fileMimeType)) {
            Path tempFile = saveFileToTempDir(fileExtension, originalFileBytes);
            if (tempFile == null) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: checkMimeType failed: tempFile is null");
                logWarn(sharedStringBuilder);
                return false;
            }
            try {
                fileMimeType = Files.probeContentType(tempFile);
            } catch (Exception e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: checkMimeType failed: ").append(e.getMessage());
                logWarn(sharedStringBuilder);
            } finally {
                deleteTempDir(tempFile);
            }
        }
        return !isBlank(fileMimeType) && fileMimeType.equals(mimeType);
    }
References dev.filechampion.filechampion4j.FileValidator.deleteTempDir(), dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.FileValidator.isBlank(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.mimeString, dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir(), and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
checkPluginsConfig()
void dev.filechampion.filechampion4j.FileValidator.checkPluginsConfig () private
Method to check that all extensions defined in config exist in plugins configuration from Validation.json
Definition at line 582 of file FileValidator.java.
{
        // check that all extensions defined plugins exist in maps
        JSONObject validationsJsonObject = configJsonObject.getJSONObject("Validations");
        for (int i = 0; i < validationsJsonObject.length(); i++) {
            String categroyKey = validationsJsonObject.names().getString(i);
            for (int k=0; k < validationsJsonObject.getJSONObject(categroyKey).length(); k++) {
                String extensionKey = validationsJsonObject.getJSONObject(categroyKey).names().getString(k);
                if (validationsJsonObject.getJSONObject(categroyKey).getJSONObject(extensionKey).has("extension_plugins")) {
                    checkPluginsExist(validationsJsonObject, categroyKey, extensionKey);
                }
            }
        }
    }
References dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), and dev.filechampion.filechampion4j.FileValidator.configJsonObject.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator().
checkPluginsExist()
void dev.filechampion.filechampion4j.FileValidator.checkPluginsExist (JSONObject validationsJsonObject, String categroyKey, String extensionKey) private
Method to check that each extension defined in config exist in plugins configuration
Parameters
validationsJsonObject (JSONObject) - the validations.json object
categroyKey (String) - the category key
extensionKey (String) - the extension key
Definition at line 602 of file FileValidator.java.
{
        for (String pluginName : validationsJsonObject.getJSONObject(categroyKey).getJSONObject(extensionKey).getJSONArray("extension_plugins").toList().toArray(new String[0])) {
            if (!stepConfigsBefore.containsKey(pluginName) && !stepConfigsAfter.containsKey(pluginName)) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), sharedStepMessage).append(pluginName).append(" defined in config does not exist in plugins configuration");
                logWarn(sharedStringBuilder);
                throw new IllegalArgumentException(sharedStringBuilder.toString());
            }
        }
    }
References dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.sharedStepMessage, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, dev.filechampion.filechampion4j.FileValidator.stepConfigsAfter, and dev.filechampion.filechampion4j.FileValidator.stepConfigsBefore.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkPluginsConfig().
containsFooterSignatures()
boolean dev.filechampion.filechampion4j.FileValidator.containsFooterSignatures (byte[] fileBytes, String footerSignaturesPattern) private
Check if the file contains the expected footer signatures
Parameters
fileBytes (byte[]) the file bytes of the file being validated
footerSignaturesPattern (String) the expected footer signatures of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected footer signatures, false otherwise
Definition at line 964 of file FileValidator.java.
{
        if (isBlank(footerSignaturesPattern)) {
            return true;
        }
        String hexPattern = footerSignaturesPattern.replaceAll("\\p{Zs}", "");
        if (hexPattern.length() % 2 != 0) {
            hexPattern = "0" + hexPattern;
        }
        byte[] footerSignatures = new byte[hexPattern.length() / 2];
        for (int i = 0; i < hexPattern.length(); i += 2) {
            footerSignatures[i / 2] = (byte) Integer.parseInt(hexPattern.substring(i, i + 2), 16);
        }
        int footerStartIndex = fileBytes.length - footerSignatures.length -1;
        if (footerStartIndex < 0) {
            return false;
        }
        for (int i = 0; i < footerSignatures.length; i++) {
            if (fileBytes[footerStartIndex + i] != footerSignatures[i]) {
                return false;
            }
        }
        return true;
    }
References dev.filechampion.filechampion4j.FileValidator.isBlank().
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
containsHeaderSignatures()
boolean dev.filechampion.filechampion4j.FileValidator.containsHeaderSignatures (byte[] fileBytes, String headerSignaturesPattern) private
Check if the file contains the expected header signatures
Parameters
fileBytes (byte[]) the file bytes of the file being validated
headerSignaturesPattern (String) the expected header signatures of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected header signatures, false otherwise
Definition at line 938 of file FileValidator.java.
{
        if (isBlank(headerSignaturesPattern)) {
            return true;
        }
        String hexPattern = headerSignaturesPattern.replaceAll("\\p{Zs}", "");
        if (hexPattern.length() % 2 != 0) {
            hexPattern = "0" + hexPattern;
        }
        byte[] headerSignatures = new byte[hexPattern.length() / 2];
        for (int i = 0; i < hexPattern.length(); i += 2) {
            headerSignatures[i / 2] = (byte) Integer.parseInt(hexPattern.substring(i, i + 2), 16);
        }
        for (int i = 0; i < headerSignatures.length; i++) {
            if (i >= fileBytes.length || fileBytes[i] != headerSignatures[i]) {
                return false;
            }
        }
        return true;
    }
References dev.filechampion.filechampion4j.FileValidator.isBlank().
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
containsMagicBytes()
boolean dev.filechampion.filechampion4j.FileValidator.containsMagicBytes (byte[] originalFileBytes, String magicBytesPattern) private
Check if the file contains the expected magic bytes
Parameters
originalFileBytes (byte[]) the file bytes of the file being validated
magicBytesPattern (String) the expected magic bytes of the file being validated
Returns
Boolean (Boolean) true if the file contains the expected magic bytes, false otherwise
Definition at line 905 of file FileValidator.java.
{
        if (originalFileBytes.length == 0 || magicBytesPattern == null || magicBytesPattern.isEmpty()) {
            return false;
        }
        magicBytesPattern = magicBytesPattern.replaceAll("\\p{Zs}", "");
        if (magicBytesPattern.length() % 2 != 0) {
            magicBytesPattern = "0" + magicBytesPattern;
        }
        byte[] magicBytes = new byte[magicBytesPattern.length() / 2];
        for (int i = 0; i < magicBytesPattern.length(); i += 2) {
            magicBytes[i / 2] = (byte) Integer.parseInt(magicBytesPattern.substring(i, i + 2), 16);
        }
        for (int i = 0; i < originalFileBytes.length - magicBytes.length; i++) {
            boolean found = true;
            for (int j = 0; j < magicBytes.length; j++) {
                if (originalFileBytes[i + j] != magicBytes[j]) {
                    found = false;
                    break;
                }
            }
            if (found) {
                return true;
            }
        }
        return false;
    }
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
deleteTempDir()
Boolean dev.filechampion.filechampion4j.FileValidator.deleteTempDir (Path tempFilePath) private
Helper method to delete the temporary directory
Parameters
tempFilePath (Path) the path to the temporary file
Returns
Boolean (Boolean) true if the temporary directory was deleted successfully, false otherwise
Definition at line 845 of file FileValidator.java.
{
        try (Stream<Path> walk = Files.walk(tempFilePath)) {
            walk.sorted(Comparator.reverseOrder())
            .map(Path::toFile)
            .forEach(File::delete);
            return true;
        } catch (Exception e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Delete temporary directoy failed: ").append(e.getMessage());
            logWarn(sharedStringBuilder);
            return false;
        }
    }
References dev.filechampion.filechampion4j.FileValidator.logWarn(), and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMimeType(), and dev.filechampion.filechampion4j.FileValidator.executePlugin().
doValidations()
ValidationResponse dev.filechampion.filechampion4j.FileValidator.doValidations (String originalFilenameClean) private
Following initial validations and before plugins, this method is used to execute the validations for the file.
Parameters
originalFilenameClean (String) a string containing the cleaned file name
Returns
ValidationResponse (ValidationResponse) a ValidationResponse object containing the results of the validation
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 357 of file FileValidator.java.
{
        // Check that the file size is not greater than the maximum allowed size, dont continue if it is
        int maxSize;
        try {
            maxSize = Integer.parseInt(extensions.getValidationValue(fileCategory, fileExtension, "max_size") != null ? extensions.getValidationValue(fileCategory, fileExtension, "max_size").toString() : "-1");
        } catch (NumberFormatException e) {
            maxSize = -1;
        }
        if (maxSize > -1 && Boolean.FALSE.equals(checkFileSize(originalFile.length, maxSize))) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("File size (")
                .append(originalFile.length / 1000)
                .append("KB) exceeds maximum allowed size (")
                .append(maxSize)
                .append("KB)")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
            return new ValidationResponse(false, errorResponse, sbresponseAggregationFail.toString(), originalFilenameClean, originalFile, "");
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("File size check passed, file size: ")
                .append(originalFile.length / 1000)
                .append("KB");
            logFine(sbresponseAggregationSuccess);
        }
        // Check that the mime type is allowed
        String mimeType = (String) extensions.getValidationValue(fileCategory, fileExtension, "mime_type");
        if (!isBlank(mimeType) && !checkMimeType(originalFile, fileExtension, mimeType)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid mime_type")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Mime type check passed, mime type: ")
                .append(mimeType);
            logFine(sbresponseAggregationSuccess);
        }
        // Check that the file contains the magic bytes
        String magicBytes = (String) extensions.getValidationValue(fileCategory, fileExtension, "magic_bytes");
        if (!isBlank(magicBytes) && !containsMagicBytes(originalFile, magicBytes)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid magic_bytes")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Magic bytes check passed, magic bytes: ")
                .append(magicBytes);
            logFine(sbresponseAggregationSuccess);
        }
        // Check header signatures
        String headerSignatures = (String) extensions.getValidationValue(fileCategory, fileExtension, "header_signatures");
        if (!isBlank(headerSignatures) && !containsHeaderSignatures(originalFile, headerSignatures)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid header_signatures")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Header signatures check passed, header signatures: ")
                .append(headerSignatures);
            logFine(sbresponseAggregationSuccess);
        }
        // Check footer signatures
        String footerSignatures = (String) extensions.getValidationValue(fileCategory, fileExtension, "footer_signatures");
        if (!isBlank(footerSignatures) && !containsFooterSignatures(originalFile, footerSignatures)) {
            sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                .append("Invalid footer_signatures")
                .append(commonLogString);
            logWarn(sbresponseAggregationFail);
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("Footer signatures check passed, footer signatures: ")
                .append(footerSignatures);
            logFine(sbresponseAggregationSuccess);
        }
        // Check for after plugins
        if (extensions.getValidationValue(fileCategory, fileExtension, "extension_plugins") != null) {
            String executionResults = executeAfterPlugins(fileCategory, fileExtension);
            if (executionResults.contains(". Failed for step:")) {
                sbresponseAggregationFail.append(System.lineSeparator() + ++responseMsgCountFail + ". ")
                    .append("Error in executeAfterPlugins: ")
                    .append(executionResults)
                    .append(commonLogString);
                logWarn(sbresponseAggregationFail);
            } else if (executionResults.contains(". Error for step:")) {
                sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("executeAfterPlugins passed with error: ")
                    .append(executionResults);
                logFine(sbresponseAggregationSuccess);
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error in executeAfterPlugins: ").append(executionResults);
                logWarn(sharedStringBuilder);
            } else {
                sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("executeAfterPlugins executed successfully: ")
                    .append(executionResults);
                logFine(sbresponseAggregationSuccess);
            }
        } else {
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("No after plugins to execute");
            logFine(sbresponseAggregationSuccess);
        }
        boolean isAddChecksum = extensions.getValidationValue(fileCategory, fileExtension, "add_checksum") != null
        ? (boolean) extensions.getValidationValue(fileCategory, fileExtension, "add_checksum") : true;
        String checksumString = isAddChecksum ? calculateChecksum(originalFile) : "";
        // Check if file passed all defined validations, return false and reason if not.
        if (responseMsgCountFail > 0) {
            logWarn(sbresponseAggregationFail);
            return new ValidationResponse(false, errorResponse, sbresponseAggregationFail.toString(), originalFilenameClean, originalFile, checksumString);
        }
        // Check if the file name should be encoded
        String encodedFileName = "";
        boolean isNameEncoding = extensions.getValidationValue(fileCategory, fileExtension, "name_encoding") != null ? (boolean) extensions.getValidationValue(fileCategory, fileExtension, "name_encoding") : false;
        if (isNameEncoding) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), Base64.getEncoder().encodeToString(originalFilenameClean.getBytes(StandardCharsets.UTF_8))).append(".").append(fileExtension);
            encodedFileName = sharedStringBuilder.toString();
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("File name: ")
                    .append(originalFilenameClean)
                    .append(" has been successfully encoded to: ")
                    .append(encodedFileName);
            logFine(sbresponseAggregationSuccess);
        }
        String targetFileName = encodedFileName.isEmpty() ? originalFilenameClean : encodedFileName;
        // Check if the file should be saved to output directory
        String savedFilePath;
        if (outDir != null && !isBlank(outDir.toString())) {
            savedFilePath = saveFileToOutputDir(fileCategory, fileExtension, outDir, targetFileName, originalFile);
            if (savedFilePath.contains("Error:")) {
                // Return valid file response if file failed to save to output directory
                sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("File is valid but failed to save to output directory: ")
                    .append(savedFilePath);
                logInfo(sbresponseAggregationSuccess);
                return new ValidationResponse(true, "File is valid but failed to save to output directory", sbresponseAggregationSuccess.toString(), originalFilenameClean, originalFile, checksumString);
            }
            // Return valid file response if file was saved to output directory
            sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                .append("File is valid and was saved to output directory: ")
                .append(savedFilePath);
            logInfo(sbresponseAggregationSuccess);
            return new ValidationResponse(true, "File is valid and was saved to output directory", sbresponseAggregationSuccess.toString(), originalFilenameClean, originalFile, checksumString);
        }
        // Return valid response if file passed all validations but is not meant to be saved to disk
        sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
            .append("File is valid: ")
            .append(originalFilenameClean);
        logInfo(sbresponseAggregationSuccess);
        return new ValidationResponse(true, "File is valid", sbresponseAggregationSuccess.toString(), originalFilenameClean, originalFile, checksumString);
    }
References dev.filechampion.filechampion4j.FileValidator.calculateChecksum(), dev.filechampion.filechampion4j.FileValidator.checkFileSize(), dev.filechampion.filechampion4j.FileValidator.checkMimeType(), dev.filechampion.filechampion4j.FileValidator.commonLogString, dev.filechampion.filechampion4j.FileValidator.containsFooterSignatures(), dev.filechampion.filechampion4j.FileValidator.containsHeaderSignatures(), dev.filechampion.filechampion4j.FileValidator.containsMagicBytes(), dev.filechampion.filechampion4j.FileValidator.errorResponse, dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.FileValidator.isBlank(), dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logInfo(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.outDir, dev.filechampion.filechampion4j.FileValidator.responseMsgCountFail, dev.filechampion.filechampion4j.FileValidator.responseMsgCountSuccess, dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationFail, dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationSuccess, and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFileMain().
executeAfterPlugins()
String dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins (String fileCategory, String fileExtension) private
Execute and check results of plugins configured to run after the validations
Parameters
fileCategory (String) the file category of the file being validated
fileExtension (String) the file extension of the file being validated
Returns
String (String) a string containing the results of the plugin execution
Definition at line 688 of file FileValidator.java.
{
        String responseAggregation = "";
        char responseMsgCount = 'a';
        StringBuilder sbResponseAggregation = new StringBuilder(responseAggregation);
        ArrayList plugins = (ArrayList) extensions.getValidationValue(fileCategory, fileExtension, "extension_plugins");
        for (int i = 0; i < plugins.size(); i++) {
            String extensionPlugin = (String) plugins.get(i);
            for (String step : stepConfigsAfter.keySet()) {
                if (step.equals(extensionPlugin)) {
                    String stepResults = executePlugin(extensionPlugin, stepConfigsAfter, fileExtension);
                    sharedStringBuilder.replace(0, sharedStringBuilder.length(), sharedStepMessage)
                        .append(stepConfigsAfter.get(extensionPlugin).getName()).append(" Success, Results: Error");
                    String sharedString = ", Results: ";
                    if (stepResults.startsWith(sharedStringBuilder.toString()) || stepResults.startsWith("Error ")) {
                        if (stepConfigsAfter.get(extensionPlugin).getOnFail().equals("fail")) {
                            sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                                .append("Failed for step: ")
                                .append(stepConfigsAfter.get(extensionPlugin).getName())
                                .append(sharedString)
                                .append(stepResults);
                            logFine(sbResponseAggregation);
                            return sbResponseAggregation.toString();
                        }
                        sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                            .append("Error for step: ")
                            .append(stepConfigsAfter.get(extensionPlugin).getName())
                            .append(sharedString + stepResults);
                        logFine(sbResponseAggregation);
                        ++responseMsgCount;
                        responseAggregation = sbResponseAggregation.toString();
                    } else {
                        sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                            .append("Success for step: ")
                            .append(stepConfigsAfter.get(extensionPlugin).getName());
                        logFine(sbResponseAggregation);
                        ++responseMsgCount;
                    }
                }
            }
        }
        return "executeAfterPlugins completed: " + sbResponseAggregation.toString();
    }
References dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.sharedStepMessage, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.stepConfigsAfter.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
executeBeforePlugins()
String dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins (String fileCategory, String fileExtension) private
Execute and check results of plugins configured to run before the validations
Parameters
fileCategory (String) the file category of the file being validated
fileExtension (String) the file extension of the file being validated
Returns
String (String) a string containing the results of the plugin execution
Definition at line 637 of file FileValidator.java.
{
        String responseAggregation = "";
        char responseMsgCount = 'a';
        StringBuilder sbResponseAggregation = new StringBuilder(responseAggregation);
        ArrayList plugins = (ArrayList) extensions.getValidationValue(fileCategory, fileExtension, "extension_plugins");
        for (int i = 0; i < plugins.size(); i++) {
            String extensionPlugin = (String) plugins.get(i);
            for (String step : stepConfigsBefore.keySet()) {
                if (step.equals(extensionPlugin)) {
                    String stepResults = executePlugin(extensionPlugin, stepConfigsBefore, fileExtension);
                    sharedStringBuilder.replace(0, sharedStringBuilder.length(), sharedStepMessage)
                        .append(stepConfigsBefore.get(extensionPlugin).getName()).append(" Success, Results: Error");
                    String sharedString = ", Results: ";
                    if (stepResults.startsWith(sharedStringBuilder.toString()) || stepResults.startsWith("Error ")) {
                        if (stepConfigsBefore.get(extensionPlugin).getOnFail().equals("fail")) {
                            sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                                .append("Failed for step: ")
                                .append(stepConfigsBefore.get(extensionPlugin).getName())
                                .append(sharedString)
                                .append(stepResults);
                            logFine(sbResponseAggregation);
                            return sbResponseAggregation.toString();
                        }
                        sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                            .append("Error for step: ")
                            .append(stepConfigsBefore.get(extensionPlugin).getName())
                            .append(sharedString + stepResults);
                        logFine(sbResponseAggregation);
                        ++responseMsgCount;
                        responseAggregation = sbResponseAggregation.toString();
                    } else {
                        sbResponseAggregation.append(System.lineSeparator()).append("\t")  .append(responseMsgCount + ". ")
                            .append("Success for step: ")
                            .append(stepConfigsBefore.get(extensionPlugin).getName());
                        logFine(sbResponseAggregation);
                        ++responseMsgCount;
                    }
                }
            }
        }
        return "executeBeforePlugins completed: " + sbResponseAggregation.toString();
    }
References dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.sharedStepMessage, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.stepConfigsBefore.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFileMain().
executePlugin()
String dev.filechampion.filechampion4j.FileValidator.executePlugin (String extensionPlugin, Map< String, StepConfig > stepConfigs, String fileExtension) private
Execute a single plugin step
Parameters
extensionPlugin (String) a string containing the name of the plugin step to execute
stepConfigs (Map<String, StepConfig>) a map containing the configuration for the step to execute
fileExtension (String) the file extension of the file being validated
Returns
String (String) a string containing the results of the plugin execution
Definition at line 739 of file FileValidator.java.
{
        Map<String, String> stepResultsMap = new HashMap<>();
        String extensionPluginName = stepConfigs.get(extensionPlugin).getName();
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), sharedStepMessage).append(extensionPluginName);
        logFine(sharedStringBuilder);
        if (stepConfigs.get(extensionPlugin).getType().equals("cli")) {
            Map<String, Map<String, String>> stepResults = stepConfigs.get(extensionPlugin)
                .getCliPluginHelper()
                .execute(fileExtension, originalFile);
            stepResultsMap.putAll(stepResults.get(stepResults.keySet().toArray()[0]));
            if (!stepResultsMap.isEmpty() && stepResults.containsKey("Success")) {
                String newFilePath = stepResultsMap.get(extensionPluginName.substring(extensionPluginName.lastIndexOf(".")+1,
                extensionPluginName.length()) + ".filePath");
                String newB64Content = stepResultsMap.get(extensionPluginName.substring(extensionPluginName.lastIndexOf(".")+1,
                extensionPluginName.length()) + ".fileContent");
                if (!isBlank(newFilePath)) {
                    try {
                        Path newFile = new File(newFilePath).toPath();
                        originalFile = Files.readAllBytes(newFile);
                        deleteTempDir(newFile.getParent().toAbsolutePath());
                        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Successfully read plugin expected file: ").append(newFilePath);
                        logFine(sharedStringBuilder);
                    } catch (IOException e) {
                        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error reading plugin expected file: ").append(e.getMessage());
                        logWarn(sharedStringBuilder);
                        return sharedStringBuilder.toString();
                    }
                }
                if (!isBlank(newB64Content)) {
                    try {
                        originalFile = Base64.getDecoder().decode(newB64Content);
                        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Successfully decoded plugin expected file");
                        logFine(sharedStringBuilder);
                    } catch (Exception e) {
                        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error decoding plugin expected file: ").append(e.getMessage());
                        logWarn(sharedStringBuilder);
                        return sharedStringBuilder.toString();
                    }
                }
            }
            for(Map.Entry<String, String> entry : stepResultsMap.entrySet()) {
                String errorMsg =  entry.getValue();
                String errorDetails = entry.getKey();
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), sharedStepMessage).append(extensionPluginName)
                    .append(" Success, Results: ")
                    .append(errorDetails)
                    .append("\"")
                    .append(errorMsg);
                logFine(sharedStringBuilder);
            }
            return sharedStringBuilder.toString();
        } else if (stepConfigs.get(extensionPlugin).getType().equals("http")) {
            // TODO: Implement http plugin type
        }
        return sharedStringBuilder.toString();
    }
References dev.filechampion.filechampion4j.FileValidator.deleteTempDir(), dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.FileValidator.isBlank(), dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStepMessage, and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), and dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins().
getFileExtension()
String dev.filechampion.filechampion4j.FileValidator.getFileExtension (String fileName) private
Parse the file extension from the file name
Parameters
fileName (String) the name of the file being validated
Returns
String (String) the file extension of the file being validated
Definition at line 891 of file FileValidator.java.
{
        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex == -1 || dotIndex == fileName.length() - 1) {
            return "";
        }
        return fileName.substring(dotIndex + 1);
    }
References dev.filechampion.filechampion4j.FileValidator.fileName.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFileMain().
isBlank()
boolean dev.filechampion.filechampion4j.FileValidator.isBlank (String str) private
isBlank wrapper method for support of Java 8
Parameters
str (String) the string to check if empty or null
Returns
boolean (boolean) true if the string is empty or null, false otherwise
Definition at line 805 of file FileValidator.java.
{
        return str == null || str.trim().isEmpty();
    }
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMethodInputs(), dev.filechampion.filechampion4j.FileValidator.checkMimeType(), dev.filechampion.filechampion4j.FileValidator.containsFooterSignatures(), dev.filechampion.filechampion4j.FileValidator.containsHeaderSignatures(), dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.executePlugin().
loadPlugins()
void dev.filechampion.filechampion4j.FileValidator.loadPlugins () private
Method to load the plugins objects into maps
Definition at line 569 of file FileValidator.java.
{
        for (PluginConfig pluginConfig : pluginsHelper.getPluginConfigs().values()) {
            for (String step : pluginConfig.getStepConfigs().keySet()) {
                StepConfig stepConfig = pluginConfig.getStepConfigs().get(step);
                stepConfigsBefore.put(stepConfig.isRunBefore()? step : "", stepConfig.isRunBefore()? stepConfig : null);
                stepConfigsAfter.put(stepConfig.isRunAfter()? step : "", stepConfig.isRunAfter()? stepConfig : null);
            }
        }
    }
References dev.filechampion.filechampion4j.PluginsHelper.getPluginConfigs(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunAfter(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.isRunBefore(), dev.filechampion.filechampion4j.FileValidator.pluginsHelper, dev.filechampion.filechampion4j.FileValidator.stepConfigsAfter, and dev.filechampion.filechampion4j.FileValidator.stepConfigsBefore.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator().
logFine()
void dev.filechampion.filechampion4j.FileValidator.logFine (StringBuilder message) private
LOGGER.fine wrapper
Parameters
message (StringBuilder) - message to log
Definition at line 560 of file FileValidator.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message.toString());
        }
    }
References dev.filechampion.filechampion4j.FileValidator.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
logInfo()
void dev.filechampion.filechampion4j.FileValidator.logInfo (StringBuilder message) private
LOGGER.info wrapper
Parameters
message (String) - message to log
Definition at line 530 of file FileValidator.java.
{
        if (LOGGER.isLoggable(Level.INFO)) {
            LOGGER.info(message.toString());
        }
    }
References dev.filechampion.filechampion4j.FileValidator.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
logSevere()
void dev.filechampion.filechampion4j.FileValidator.logSevere (StringBuilder message) private
LOGGER.severe wrapper
Parameters
message (String) - message to log
Definition at line 550 of file FileValidator.java.
{
        if (LOGGER.isLoggable(Level.SEVERE)) {
            LOGGER.severe(message.toString());
        }
    }
References dev.filechampion.filechampion4j.FileValidator.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), and dev.filechampion.filechampion4j.FileValidator.setFileAttributes().
logWarn()
void dev.filechampion.filechampion4j.FileValidator.logWarn (StringBuilder message) private
LOGGER.warning wrapper
Parameters
message (String) - message to log
Definition at line 540 of file FileValidator.java.
{
        if (LOGGER.isLoggable(Level.WARNING)) {
            LOGGER.warning(message.toString());
        }
    }
References dev.filechampion.filechampion4j.FileValidator.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator(), dev.filechampion.filechampion4j.FileValidator.checkMimeType(), dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), dev.filechampion.filechampion4j.FileValidator.deleteTempDir(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
saveFileToOutputDir()
String dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir (String fileCategory, String fileExtension, Path outDir, String fileName, byte[] fileBytes) private
Helper method to save the file defined file attributes to the output directory and return the path to the saved file
Parameters
fileCategory (String) the file category of the file being validated
fileExtension (String) the file extension of the file being validated
outDir (Path) the path to the output directory
fileName (String) the name of the file being validated
fileBytes (byte[]) the file bytes of the file being validated
Returns
String (String) the path to the saved file
Definition at line 1013 of file FileValidator.java.
{
        Path targetFilePath = Paths.get(outDir.toString(), fileName);
        try {
            Files.write(targetFilePath, fileBytes, StandardOpenOption.CREATE);
        } catch (IOException e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Saving file to directory failed: ").append(e.getMessage());
            logSevere(sharedStringBuilder);
            return sharedStringBuilder.toString();
        }
        boolean changeOwnership = extensions.getValidationValue(fileCategory, fileExtension, "change_ownership") != null
        ? (boolean) extensions.getValidationValue(fileCategory, fileExtension, "change_ownership") : false;
        if (changeOwnership) {
            String changeOwnershipUser = (String) extensions.getValidationValue(fileCategory, fileExtension, "change_ownership_user");
            String changePermissionsMode = (String) extensions.getValidationValue(fileCategory, fileExtension, "change_ownership_mode");
            String changeOwnershipStatus = setFileAttributes(targetFilePath, changeOwnershipUser, changePermissionsMode);
            if (changeOwnershipStatus.contains("Error:")) {
                return changeOwnershipStatus;
            }
        }
        return targetFilePath.toAbsolutePath().toString();
    }
References dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.FileValidator.logSevere(), dev.filechampion.filechampion4j.FileValidator.outDir, dev.filechampion.filechampion4j.FileValidator.setFileAttributes(), and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations().
saveFileToTempDir()
Path dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir (String fileExtension, byte[] originalFile) private
Helper method to save the file to a temporary directory
Parameters
fileExtension (String) the file extension of the file being validated
originalFile (byte[]) the file bytes of the file being validated
Returns
Path (Path) the path to the temporary file
Definition at line 825 of file FileValidator.java.
{
        Path tempFilePath = null;
        try {
            // Create a temporary directory
            Path tempDir = Files.createTempDirectory("tempDir");
            tempFilePath = Files.createTempFile(tempDir, "tempFile", "." + fileExtension);
            Files.write(tempFilePath, originalFile);
        } catch (Exception e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Saving file to temporary directory failed: ").append(e.getMessage());
            logWarn(sharedStringBuilder);
            return null;
        }
        return tempFilePath;
    }
References dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMimeType().
setFileAttributes()
String dev.filechampion.filechampion4j.FileValidator.setFileAttributes (Path targetFilePath, String changeOwnershipUser, String changePermissionsMode) private
Helper method to set the file attributes
Parameters
targetFilePath (Path) the path to the file
changeOwnershipUser (String) the user to change the ownership to
changePermissionsMode (String) the permissions to change the file to
Returns
String (String) the status of the file attribute change
Definition at line 1043 of file FileValidator.java.
{
        FileAclHelper fileAclHelper = new FileAclHelper(targetFilePath, changeOwnershipUser, changePermissionsMode);
        String newFileAttributesStatus = fileAclHelper.changeFileAcl();
        if (newFileAttributesStatus.contains("Error:")) {
            try {
                Files.deleteIfExists(targetFilePath);
            } catch (IOException e) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error: Failed to delete file from permissions change operation: ").append(e.getMessage());
                logSevere(sharedStringBuilder);
            }
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), newFileAttributesStatus);
            logSevere(sharedStringBuilder);
            return newFileAttributesStatus;
        } else {
            return "Success: File attributes changed successfully";
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileValidator.logSevere(), and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir().
validateFile() [1/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, byte[] originalFile, String fileName)
This method is used to validate the file as file bytes, and return the results.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
originalFile (byte[]) - The file to be validated as a byte array.
fileName (String) - The original name of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 263 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating file bytes of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.originalFile = originalFile;
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [2/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, byte[] originalFile, String fileName, Path outputDir)
This method is used to validate the file as file bytes, save the file to the output directory if passed validations, and return the results.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
originalFile (byte[]) - The file to be validated as a byte array.
fileName (String) - The original name of the file to be validated.
outputDir (Path) - The directory to save the file to if it passes validations.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 186 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating and Storing file bytes of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.originalFile = originalFile;
        this.outDir = outputDir;
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [3/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, byte[] originalFile, String fileName, Path outputDir, String mimeString)
This method is used to validate the file bytes with existing mime type, typically present in web related file uploads, and save the file to the output directory if passed validations.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
originalFile (byte[]) - The file to be validated as a byte array.
fileName (String) - The original name of the file to be validated.
outputDir (Path) - The directory to save the file to if it passes validations.
mimeString (String) - The mime type of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 108 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating with request mime ")
            .append(mimeString)
            .append(" and storage for file bytes of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.originalFile = originalFile;
        this.mimeString = mimeString;
        this.outDir = outputDir;
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.mimeString, dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [4/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, byte[] originalFile, String fileName, String mimeString)
This method is used to validate the file as file bytes, with existing mime type, typically present in web related file uploads.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
originalFile (byte[]) - The file to be validated as a byte array.
fileName (String) - The original name of the file to be validated.
mimeString (String) - The mime type of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 164 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating with request ")
            .append(mimeString)
            .append(" mime for file bytes of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.originalFile = originalFile;
        this.mimeString = mimeString;
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.mimeString, dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [5/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, Path filePath, String fileName)
This method is used to validate the file in target path, and return the results.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
filePath (Path) - The target file path to be validated as a String.
fileName (String) - The original name of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 281 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating file path of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        try {
            Path path = filePath;
            originalFile = Files.readAllBytes(path);
        } catch (IOException e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), commonFileError)
                .append(e.getMessage());
            logWarn(sharedStringBuilder);
            throw new IllegalArgumentException(commonFileError + e.getMessage());
        }
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.commonFileError, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [6/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, Path filePath, String fileName, Path outputDir)
This method is used to validate the file in target path, save the file to the output directory if passed validations, and return the results.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
filePath (Path) - The target file path to be validated as a String.
fileName (String) - The original name of the file to be validated.
outputDir (Path) - The directory to save the file to if it passes validations.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 236 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating and Storing file path of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.outDir = outputDir;
        try {
            Path path = filePath;
            originalFile = Files.readAllBytes(path);
        } catch (IOException e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), commonFileError)
                .append(e.getMessage());
            logWarn(sharedStringBuilder);
            throw new IllegalArgumentException(commonFileError + e.getMessage());
        }
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.commonFileError, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [7/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, Path filePath, String fileName, Path outputDir, String mimeString)
This method is used to validate the file path with existing mime type, typically present in web related file uploads, and save the file to the output directory if passed validations.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
filePath (Path) - The target file path to be validated as a String.
fileName (String) - The original name of the file to be validated.
outputDir (Path) - The directory to save the file to if it passes validations.
mimeString (String) - The mime type of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 133 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating with request mime ")
            .append(mimeString)
            .append(" and storage for file path of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.mimeString = mimeString;
        this.outDir = outputDir;
        try {
            Path path = filePath;
            originalFile = Files.readAllBytes(path);
        } catch (IOException e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), commonFileError)
                .append(e.getMessage());
            logWarn(sharedStringBuilder);
            throw new IllegalArgumentException(commonFileError + e.getMessage());
        }
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.commonFileError, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.mimeString, dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFile() [8/8]
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFile (String fileCategory, Path filePath, String fileName, String mimeString)
This method is used to validate the file path with existing mime type, typically present in web related file uploads.
Parameters
fileCategory (String) - The category of the file to be validated. This is used to determine which validations to run.
filePath (Path) - The target file path to be validated as a String.
fileName (String) - The original name of the file to be validated.
mimeString (String) - The mime type of the file to be validated.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 206 of file FileValidator.java.
{
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating with request mime ")
            .append(mimeString)
            .append(" for file path of: ")
            .append(fileName);
        logFine(sharedStringBuilder);
        this.fileCategory = fileCategory;
        this.fileName = fileName;
        this.mimeString = mimeString;
        try {
            Path path = filePath;
            originalFile = Files.readAllBytes(path);
        } catch (IOException e) {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), commonFileError)
                .append(e.getMessage());
            logWarn(sharedStringBuilder);
            throw new IllegalArgumentException(commonFileError + e.getMessage());
        }
        return validateFileMain();
    }
References dev.filechampion.filechampion4j.FileValidator.commonFileError, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.mimeString, dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder, and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
validateFileMain()
ValidationResponse dev.filechampion.filechampion4j.FileValidator.validateFileMain () private
This method is the internal entry point for the file validation process.
Returns
(ValidationResponse) - The results of the validations.
Exceptions
IllegalArgumentException - If any of the required inputs are null or empty.
Definition at line 304 of file FileValidator.java.
{
        commonLogString = String.format(" for file extension: %s", fileExtension);
        responseMsgCountFail = 0;
        sbresponseAggregationFail = new StringBuilder("");
        responseMsgCountSuccess = 0;
        sbresponseAggregationSuccess = new StringBuilder("");
        // Check that the input parameters are not null or empty
        checkMethodInputs(fileCategory, originalFile, fileName);
        // Initialize variables
        fileExtension = getFileExtension(fileName);
        String originalFilenameClean = fileName.replaceAll("[^\\p{IsAlphabetic}\\p{IsDigit}.]", "_");
        // Log the file type category being validated
        sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Validating ").append(originalFilenameClean).append(", as file type: ").append(fileCategory);
        logInfo(sharedStringBuilder);
        // Check for before plugins
        if (extensions.getValidationValue(fileCategory, fileExtension, "extension_plugins") != null) {
            String executionResults = executeBeforePlugins(fileCategory, fileExtension);
            if (executionResults.contains(". Failed for step:")) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "executeBeforePlugins failed for file: ").append(originalFilenameClean).append(", Results: ").append(executionResults);
                logWarn(sharedStringBuilder);
                return new ValidationResponse(false, errorResponse, sharedStringBuilder.toString() , originalFilenameClean, null, null);
            } else if (executionResults.contains(". Error for step:")) {
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), "Error executing Plugins defined to run before validations for file: ").append(originalFilenameClean).append(", Results: ").append(executionResults);
                sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("executeBeforePlugins passed with error: ")
                    .append(executionResults);
                logFine(sbresponseAggregationSuccess);
                logWarn(sharedStringBuilder);
            } else {
                sbresponseAggregationSuccess.append(System.lineSeparator() + ++responseMsgCountSuccess + ". ")
                    .append("executeBeforePlugins executed successfully: ")
                    .append(executionResults);
                logFine(sbresponseAggregationSuccess);
                sharedStringBuilder.replace(0, sharedStringBuilder.length(), executionResults);
                logInfo(sharedStringBuilder);
            }
        }  else {
            sharedStringBuilder.replace(0, sharedStringBuilder.length(), "No before plugins defined for file: ").append(originalFilenameClean);
            logInfo(sharedStringBuilder);
        }
        return (doValidations(originalFilenameClean));
    }
References dev.filechampion.filechampion4j.FileValidator.checkMethodInputs(), dev.filechampion.filechampion4j.FileValidator.commonLogString, dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.errorResponse, dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.extensions, dev.filechampion.filechampion4j.FileValidator.fileCategory, dev.filechampion.filechampion4j.FileValidator.fileExtension, dev.filechampion.filechampion4j.FileValidator.fileName, dev.filechampion.filechampion4j.FileValidator.getFileExtension(), dev.filechampion.filechampion4j.Extensions.getValidationValue(), dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logInfo(), dev.filechampion.filechampion4j.FileValidator.logWarn(), dev.filechampion.filechampion4j.FileValidator.originalFile, dev.filechampion.filechampion4j.FileValidator.responseMsgCountFail, dev.filechampion.filechampion4j.FileValidator.responseMsgCountSuccess, dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationFail, dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationSuccess, and dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFile().
Member Data Documentation
commonFileError
String dev.filechampion.filechampion4j.FileValidator.commonFileError = "Error reading file: " private
Definition at line 57 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.validateFile().
commonLogString
String dev.filechampion.filechampion4j.FileValidator.commonLogString private
Definition at line 58 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
configJsonObject
JSONObject dev.filechampion.filechampion4j.FileValidator.configJsonObject private
Definition at line 43 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator(), and dev.filechampion.filechampion4j.FileValidator.checkPluginsConfig().
errorResponse
String dev.filechampion.filechampion4j.FileValidator.errorResponse = "File is not valid." private
Definition at line 50 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
extensions
Extensions dev.filechampion.filechampion4j.FileValidator.extensions private
Definition at line 47 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
fileCategory
String dev.filechampion.filechampion4j.FileValidator.fileCategory private
Definition at line 51 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMethodInputs(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
fileExtension
String dev.filechampion.filechampion4j.FileValidator.fileExtension private
Definition at line 56 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMimeType(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
fileName
String dev.filechampion.filechampion4j.FileValidator.fileName private
Definition at line 52 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMethodInputs(), dev.filechampion.filechampion4j.FileValidator.getFileExtension(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
LOGGER
final Logger dev.filechampion.filechampion4j.FileValidator.LOGGER = Logger.getLogger(FileValidator.class.getName()) static private
Definition at line 42 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.logFine(), dev.filechampion.filechampion4j.FileValidator.logInfo(), dev.filechampion.filechampion4j.FileValidator.logSevere(), and dev.filechampion.filechampion4j.FileValidator.logWarn().
mimeString
String dev.filechampion.filechampion4j.FileValidator.mimeString private
Definition at line 54 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMimeType(), and dev.filechampion.filechampion4j.FileValidator.validateFile().
originalFile
byte [] dev.filechampion.filechampion4j.FileValidator.originalFile private
Definition at line 53 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkMethodInputs(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
outDir
Path dev.filechampion.filechampion4j.FileValidator.outDir private
Definition at line 55 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir().
pluginsHelper
PluginsHelper dev.filechampion.filechampion4j.FileValidator.pluginsHelper private
Definition at line 44 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator(), and dev.filechampion.filechampion4j.FileValidator.loadPlugins().
responseMsgCountFail
int dev.filechampion.filechampion4j.FileValidator.responseMsgCountFail private
Definition at line 59 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
responseMsgCountSuccess
int dev.filechampion.filechampion4j.FileValidator.responseMsgCountSuccess private
Definition at line 61 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
sbresponseAggregationFail
StringBuilder dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationFail private
Definition at line 60 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
sbresponseAggregationSuccess
StringBuilder dev.filechampion.filechampion4j.FileValidator.sbresponseAggregationSuccess private
Definition at line 62 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.doValidations(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
sharedStepMessage
String dev.filechampion.filechampion4j.FileValidator.sharedStepMessage = "Step: " private
Definition at line 49 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), and dev.filechampion.filechampion4j.FileValidator.executePlugin().
sharedStringBuilder
StringBuilder dev.filechampion.filechampion4j.FileValidator.sharedStringBuilder = new StringBuilder() private
Definition at line 48 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.FileValidator(), dev.filechampion.filechampion4j.FileValidator.checkMimeType(), dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), dev.filechampion.filechampion4j.FileValidator.deleteTempDir(), dev.filechampion.filechampion4j.FileValidator.doValidations(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), dev.filechampion.filechampion4j.FileValidator.executePlugin(), dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir(), dev.filechampion.filechampion4j.FileValidator.saveFileToTempDir(), dev.filechampion.filechampion4j.FileValidator.setFileAttributes(), dev.filechampion.filechampion4j.FileValidator.validateFile(), and dev.filechampion.filechampion4j.FileValidator.validateFileMain().
stepConfigsAfter
Map<String, StepConfig> dev.filechampion.filechampion4j.FileValidator.stepConfigsAfter = new HashMap<>() private
Definition at line 46 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), dev.filechampion.filechampion4j.FileValidator.executeAfterPlugins(), and dev.filechampion.filechampion4j.FileValidator.loadPlugins().
stepConfigsBefore
Map<String, StepConfig> dev.filechampion.filechampion4j.FileValidator.stepConfigsBefore = new HashMap<>() private
Definition at line 45 of file FileValidator.java.
Referenced by dev.filechampion.filechampion4j.FileValidator.checkPluginsExist(), dev.filechampion.filechampion4j.FileValidator.executeBeforePlugins(), and dev.filechampion.filechampion4j.FileValidator.loadPlugins().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/FileValidator.java