filechampion4j: dev.filechampion.filechampion4j.CliPluginHelper Class Reference
dev.filechampion.filechampion4j.CliPluginHelper Class Reference
Public Member Functions
CliPluginHelper (StepConfig singleStepConfig)
Map< String, Map< String, String > > execute (String fileExtension, byte[] fileContent)
Private Member Functions
void logFine (String message)
void logWarn (String message)
Map< String, String > extractResponsePatterns (String results)
void prepEndpoint (String filePath, byte[] fileContent)
String timedProcessExecution (String command) throws IOException, InterruptedException, NullPointerException
Path saveFileToTempDir (String fileExtension, byte[] originalFile)
Boolean deleteTempDir (Path tempFilePath)
String calculateChecksum (byte[] fileBytes, String checksumAlgorithm)
Private Attributes
StepConfig singleStepConfig
int timeout
String errString = "Error: "
String endpoint
String responseConfig
StringBuilder logMessage = new StringBuilder()
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(CliPluginHelper.class.getName())
Detailed Description
CliPluginHelper class is used to execute CLI commands Defined in the FileChampion Plugins. The class is responsible for injecting file path/content/hash into the CLI command, execute the command, and process the results.
Definition at line 30 of file CliPluginHelper.java.
Constructor & Destructor Documentation
CliPluginHelper()
dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper (StepConfig singleStepConfig)
Constructor for CliPluginHelper
Parameters
singleStepConfig (StepConfig) - the step configuration
Definition at line 53 of file CliPluginHelper.java.
{
        this.singleStepConfig = singleStepConfig;
        this.endpoint = singleStepConfig.getEndpoint();
        this.timeout = singleStepConfig.getTimeout();
        this.responseConfig = singleStepConfig.getResponse();
        logMessage.replace(0, logMessage.length(), singleStepConfig.getName()).append(" object created");
        logFine(logMessage.toString());
    }
References dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getEndpoint(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getName(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getResponse(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getTimeout(), dev.filechampion.filechampion4j.CliPluginHelper.logFine(), dev.filechampion.filechampion4j.CliPluginHelper.logMessage, and dev.filechampion.filechampion4j.CliPluginHelper.singleStepConfig.
Member Function Documentation
calculateChecksum()
String dev.filechampion.filechampion4j.CliPluginHelper.calculateChecksum (byte[] fileBytes, String checksumAlgorithm) private
Calculate the checksum of the file
Parameters
fileBytes (byte[]) the file bytes of the file being validated
Returns
String (String) the SHA-256 checksum of the file
Definition at line 293 of file CliPluginHelper.java.
{
        try {
            CalculateChecksum paralChecksum = new CalculateChecksum(fileBytes);
            byte[] checksum = paralChecksum.getChecksum(checksumAlgorithm);
            return new BigInteger(1, checksum).toString(16);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
References dev.filechampion.filechampion4j.CalculateChecksum.getChecksum().
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.prepEndpoint().
deleteTempDir()
Boolean dev.filechampion.filechampion4j.CliPluginHelper.deleteTempDir (Path tempFilePath) private
Deletes the temporary directory
Parameters
tempFilePath (Path) - the path to the temporary directory
Returns
Boolean - true if the directory was deleted successfully, false otherwise
Definition at line 275 of file CliPluginHelper.java.
{
        try (Stream<Path> walk = Files.walk(tempFilePath)) {
            walk.sorted(Comparator.reverseOrder())
                    .map(Path::toFile)
                    .forEach(File::delete);
            return true;
        } catch (Exception e) {
            logMessage.replace(0, logMessage.length(), "Error deleteTempDir failed: ").append(e.getMessage());
            logWarn(logMessage.toString());
            return false;
        }
    }
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
execute()
Map< String, Map< String, String > > dev.filechampion.filechampion4j.CliPluginHelper.execute (String fileExtension, byte[] fileContent)
Executes the CLI command
Parameters
fileExtension (String) - the file extension
fileContent (byte[]) - the file content
Returns
Map<String, Map<String, String>> - the results map
Definition at line 68 of file CliPluginHelper.java.
{
    String result = "";
        Map<String, Map<String, String>> responseMap = new HashMap<>();
        Map<String, String> responsePatterns = new HashMap<>();
        Path filePathRaw;
        filePathRaw = saveFileToTempDir(fileExtension, fileContent);
        if (filePathRaw == null) {
            responsePatterns.put(errString, "Failed to save file to temporary directory");
            responseMap.put(errString, responsePatterns);
            return responseMap;
        }
        String filePath = filePathRaw.toString();
        prepEndpoint(filePath, fileContent);
        logMessage.replace(0, logMessage.length(), singleStepConfig.getName()).append(" endpoint: ").append(endpoint);
        logFine(logMessage.toString());
        try {
            result = timedProcessExecution(endpoint);
            logFine(singleStepConfig.getName() + " result: " + result);
        } catch (IOException|NullPointerException|InterruptedException e) {
            Thread.currentThread().interrupt();
            responsePatterns.put(errString, e.getMessage());
        }
        String expectedResults = responseConfig.substring(0, responseConfig.indexOf("${")>-1?
        responseConfig.indexOf("${") : responseConfig.length());
        if (result.contains(expectedResults)) {
            responsePatterns = extractResponsePatterns(result);
            responseMap.put("Success", responsePatterns);
            return responseMap;
        } else {
            logMessage.replace(0, logMessage.length(), "Error, expected: \"")
                    .append(expectedResults).append("\", received: ");
            responsePatterns.put(logMessage.toString(), result);
            responseMap.put(errString, responsePatterns);
            deleteTempDir(filePathRaw);
            return responseMap;
        }
    }
References dev.filechampion.filechampion4j.CliPluginHelper.deleteTempDir(), dev.filechampion.filechampion4j.CliPluginHelper.endpoint, dev.filechampion.filechampion4j.CliPluginHelper.errString, dev.filechampion.filechampion4j.CliPluginHelper.extractResponsePatterns(), dev.filechampion.filechampion4j.PluginsHelper.StepConfig.getName(), dev.filechampion.filechampion4j.CliPluginHelper.logFine(), dev.filechampion.filechampion4j.CliPluginHelper.logMessage, dev.filechampion.filechampion4j.CliPluginHelper.prepEndpoint(), dev.filechampion.filechampion4j.CliPluginHelper.responseConfig, dev.filechampion.filechampion4j.CliPluginHelper.saveFileToTempDir(), dev.filechampion.filechampion4j.CliPluginHelper.singleStepConfig, and dev.filechampion.filechampion4j.CliPluginHelper.timedProcessExecution().
extractResponsePatterns()
Map< String, String > dev.filechampion.filechampion4j.CliPluginHelper.extractResponsePatterns (String results) private
Extracts the response patterns from the results
Parameters
results (String) - the results
Returns
Map<String, String> - the response patterns map
Definition at line 116 of file CliPluginHelper.java.
{
        Map<String, String> responsePatterns = new HashMap<>();
        // Extract the placeholder name from the response pattern
        Pattern placeholderPattern = Pattern.compile("\\$\\{(.+?)\\}");
        Matcher placeholderMatcher = placeholderPattern.matcher(responseConfig);
        if (!placeholderMatcher.find()) {
            responsePatterns.put(results, results);
            return responsePatterns;
        }
        do {
            String placeholderName = placeholderMatcher.group(1);
            String placeholderValue;
            logMessage.replace(0, logMessage.length(), "Placeholder name: ")
            .append(placeholderName)
            .append(", ResponseConfig: ")
            .append(responseConfig);
            logFine(logMessage.toString());
            String fixedPrefix = String.format("%s", responseConfig.substring(0, responseConfig.indexOf("${")));
            logMessage.replace(0, logMessage.length(), "Fixed prefix: ").append(fixedPrefix);
            logFine(logMessage.toString());
            String fixedSuffix;
            int suffixStartIndex = responseConfig.indexOf("${") + placeholderName.length() + 3;
            if (suffixStartIndex == responseConfig.length()) {
                fixedSuffix = "";
            } else {
                fixedSuffix = responseConfig.substring(suffixStartIndex);
                logMessage.replace(0, logMessage.length(), "Fixed suffix: ").append(fixedSuffix);
                logFine(logMessage.toString());
            }
            String captureGroupPattern = String.format("%s(.*)%s", fixedPrefix, fixedSuffix);
            logMessage.replace(0, logMessage.length(), "Capture group pattern: ").append(captureGroupPattern);
            logFine(logMessage.toString());
            Pattern pattern = Pattern.compile(captureGroupPattern);
            Matcher matcher = pattern.matcher(results);
            if (matcher.find()) {
                placeholderValue = matcher.group(1);
                responsePatterns.put(placeholderName, placeholderValue);
            }
        } while (placeholderMatcher.find());
        return responsePatterns;
    }
References dev.filechampion.filechampion4j.CliPluginHelper.logFine(), dev.filechampion.filechampion4j.CliPluginHelper.logMessage, and dev.filechampion.filechampion4j.CliPluginHelper.responseConfig.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
logFine()
void dev.filechampion.filechampion4j.CliPluginHelper.logFine (String message) private
Definition at line 38 of file CliPluginHelper.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message);
        }
    }
References dev.filechampion.filechampion4j.CliPluginHelper.LOGGER.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper(), dev.filechampion.filechampion4j.CliPluginHelper.execute(), dev.filechampion.filechampion4j.CliPluginHelper.extractResponsePatterns(), and dev.filechampion.filechampion4j.CliPluginHelper.timedProcessExecution().
logWarn()
void dev.filechampion.filechampion4j.CliPluginHelper.logWarn (String message) private
Definition at line 43 of file CliPluginHelper.java.
{
        if (LOGGER.isLoggable(Level.WARNING)) {
            LOGGER.warning(message);
        }
    }
References dev.filechampion.filechampion4j.CliPluginHelper.LOGGER.
prepEndpoint()
void dev.filechampion.filechampion4j.CliPluginHelper.prepEndpoint (String filePath, byte[] fileContent) private
Prepares the endpoint command by replacing the placeholders with the actual values
Parameters
filePath (String) - the path to the file
fileContent (byte[]) - the file content
Definition at line 173 of file CliPluginHelper.java.
{
        String newEndpoint = endpoint.contains("${filePath}") ? endpoint.replace("${filePath}", filePath) : endpoint;
        newEndpoint = newEndpoint.contains("${fileContent}") ? newEndpoint.replace("${fileContent}", Base64.getEncoder().encodeToString(fileContent)) : newEndpoint;
        newEndpoint = newEndpoint.contains("${fileChecksum.md5}") ? newEndpoint.replace("${fileChecksum.md5}", calculateChecksum(fileContent, "MD5")) : newEndpoint;
        newEndpoint = newEndpoint.contains("${fileChecksum.sha1}") ? newEndpoint.replace("${fileChecksum.sha1}", calculateChecksum(fileContent, "SHA-1")) : newEndpoint;
        newEndpoint = newEndpoint.contains("${fileChecksum.sha256}") ? newEndpoint.replace("${fileChecksum.sha256}", calculateChecksum(fileContent, "SHA-256")) : newEndpoint;
        newEndpoint = newEndpoint.contains("${fileChecksum.sha512}") ? newEndpoint.replace("${fileChecksum.sha512}", calculateChecksum(fileContent, "SHA-512")) : newEndpoint;
        endpoint = newEndpoint;
    }
References dev.filechampion.filechampion4j.CliPluginHelper.calculateChecksum(), and dev.filechampion.filechampion4j.CliPluginHelper.endpoint.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
saveFileToTempDir()
Path dev.filechampion.filechampion4j.CliPluginHelper.saveFileToTempDir (String fileExtension, byte[] originalFile) private
Saves the file to a temporary directory
Parameters
fileExtension (String) - the file extension
originalFile (byte[]) - the file content
Returns
Path - the path to the file
Definition at line 255 of file CliPluginHelper.java.
{
        Path tempFilePath;
        try {
            // Create a temporary directory
            Path tempDir = Files.createTempDirectory("tempDir");
            tempFilePath = Files.createTempFile(tempDir, "tempFile", "." + fileExtension);
            Files.write(tempFilePath, originalFile);
            return tempFilePath;
        } catch (Exception e) {
            logMessage.replace(0, logMessage.length(), "Error saveFileToTempDir failed: ").append(e.getMessage());
            logWarn(logMessage.toString());
            return null;
        }
    }
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
timedProcessExecution()
String dev.filechampion.filechampion4j.CliPluginHelper.timedProcessExecution (String command) throws IOException, InterruptedException, NullPointerException private
Executes the CLI command with a timeout
Parameters
command (String) - the command to execute
Returns
String - the results
Exceptions
IOException
InterruptedException
NullPointerException
Definition at line 192 of file CliPluginHelper.java.
{
        ProcessBuilder processBuilder = new ProcessBuilder(command.split("\\p{Zs}+"));
        logMessage.replace(0, logMessage.length(), "Process starting: ").append(command);
        logFine(logMessage.toString());
        long timeoutCounter = System.currentTimeMillis();
        Process process = processBuilder.start();
        TimeUnit timeUnit = TimeUnit.SECONDS;
        java.util.Timer timer = new java.util.Timer();
        timer.schedule(
            new java.util.TimerTask() {
                @Override
                public void run() {
                    process.destroy();
                }
            },
            timeUnit.toMillis(timeout)
        );
        int exitCode = process.waitFor();
        InputStream inputStream = process.getInputStream();
        InputStream errorStream = process.getErrorStream();
        SequenceInputStream sequenceInputStream = new SequenceInputStream(inputStream, errorStream);
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(sequenceInputStream));
        try(Scanner scanner = new Scanner(bufferedReader).useDelimiter("\\A")){
            String results;
            if (exitCode == 143 || exitCode == 1) {
                if (System.currentTimeMillis() - timeoutCounter > timeout * 1000) {
                    bufferedReader.close();
                    sequenceInputStream.close();
                    errorStream.close();
                    inputStream.close();
                    logMessage.replace(0, logMessage.length(), errString).append("Process timeout: ").append(command);
                    logWarn(logMessage.toString());
                    return logMessage.toString();
                }
                results = scanner.hasNext() ? scanner.next() : "";
                bufferedReader.close();
                sequenceInputStream.close();
                errorStream.close();
                inputStream.close();
                timer.cancel();
                logMessage.replace(0, logMessage.length(), errString).append(command) .append("Process failed: ").append(results);
                logWarn(logMessage.toString());
                return logMessage.toString();
            }
            results = scanner.hasNext() ? scanner.next() : "";
            bufferedReader.close();
            sequenceInputStream.close();
            errorStream.close();
            inputStream.close();
            timer.cancel();
            logFine(results);
            return results;
        }
    }
References dev.filechampion.filechampion4j.CliPluginHelper.logFine(), and dev.filechampion.filechampion4j.CliPluginHelper.logMessage.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
Member Data Documentation
endpoint
String dev.filechampion.filechampion4j.CliPluginHelper.endpoint private
Definition at line 34 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute(), and dev.filechampion.filechampion4j.CliPluginHelper.prepEndpoint().
errString
String dev.filechampion.filechampion4j.CliPluginHelper.errString = "Error: " private
Definition at line 33 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute().
LOGGER
final Logger dev.filechampion.filechampion4j.CliPluginHelper.LOGGER = Logger.getLogger(CliPluginHelper.class.getName()) static private
Definition at line 37 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.logFine(), and dev.filechampion.filechampion4j.CliPluginHelper.logWarn().
logMessage
StringBuilder dev.filechampion.filechampion4j.CliPluginHelper.logMessage = new StringBuilder() private
Definition at line 36 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper(), dev.filechampion.filechampion4j.CliPluginHelper.execute(), dev.filechampion.filechampion4j.CliPluginHelper.extractResponsePatterns(), and dev.filechampion.filechampion4j.CliPluginHelper.timedProcessExecution().
responseConfig
String dev.filechampion.filechampion4j.CliPluginHelper.responseConfig private
Definition at line 35 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.execute(), and dev.filechampion.filechampion4j.CliPluginHelper.extractResponsePatterns().
singleStepConfig
StepConfig dev.filechampion.filechampion4j.CliPluginHelper.singleStepConfig private
Definition at line 31 of file CliPluginHelper.java.
Referenced by dev.filechampion.filechampion4j.CliPluginHelper.CliPluginHelper(), and dev.filechampion.filechampion4j.CliPluginHelper.execute().
timeout
int dev.filechampion.filechampion4j.CliPluginHelper.timeout private
Definition at line 32 of file CliPluginHelper.java.
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/CliPluginHelper.java