filechampion4j: dev.filechampion.filechampion4j.FileAclHelper Class Reference
dev.filechampion.filechampion4j.FileAclHelper Class Reference
Public Member Functions
FileAclHelper (Path targetFilePath, String newOwnerUsername, String newPermissions) throws IllegalArgumentException
String changeFileAcl ()
Private Member Functions
void logSevere (String message)
void logFine (String message)
UserPrincipal getUserPrinciple (Path targetFilePath, String newOwnerUsername)
String setNewOwner (UserPrincipal newOwner)
String setNewPermissions (UserPrincipal newOwner)
String setNewPermissionsWindows (UserPrincipal newOwner)
String setNewPermissionsUnix ()
Private Attributes
Path targetFilePath
String newPermissions
String newOwnerUsername
StringBuilder errMsg = new StringBuilder()
Static Private Attributes
static final Logger LOGGER = Logger.getLogger(FileAclHelper.class.getName())
Detailed Description
This class is used to change the owner and permissions of a file. Set Owner uses java.nio.file.Files.setOwner for cross-platform support. Set Permissions attempts to identify the Operating System, using java.nio.file.attribute.AclFileAttributeView for Windows, and java.nio.file.attribute.PosixFileAttributeView for any other.
Definition at line 21 of file FileAclHelper.java.
Constructor & Destructor Documentation
FileAclHelper()
dev.filechampion.filechampion4j.FileAclHelper.FileAclHelper (Path targetFilePath, String newOwnerUsername, String newPermissions) throws IllegalArgumentException
Class constructor
Parameters
targetFilePath (Path) the path of the file to change
newOwnerUsername (String) the new owner of the file
newPermissions (String the new permissions of the file (e.g. "rwx")
Definition at line 53 of file FileAclHelper.java.
{
        this.targetFilePath = targetFilePath;
        this.newOwnerUsername = newOwnerUsername;
        if (!newPermissions.matches("[rwx]+")) {
            errMsg.replace(0, errMsg.length(), "Error: Invalid permissions:").append(newPermissions);
            throw new IllegalArgumentException(errMsg.toString());
        }
        this.newPermissions = newPermissions;
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.newOwnerUsername, dev.filechampion.filechampion4j.FileAclHelper.newPermissions, and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Member Function Documentation
changeFileAcl()
String dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl ()
changeFileAcl is the main method of this class. It attempts to change the owner and permissions of a file.
Returns
(String) a String containing the result of the operation
Definition at line 68 of file FileAclHelper.java.
{
        if(!newPermissions.matches("[rwx]+")) {
            errMsg.replace(0, errMsg.length(), "Error: Invalid permissions:").append(newPermissions);
            return errMsg.toString();
        }
        UserPrincipal newOwner = getUserPrinciple(targetFilePath, newOwnerUsername);
        if (newOwner == null) {
            errMsg.replace(0, errMsg.length(), "Error: Could not get user principal for ").append(newOwnerUsername);
            return errMsg.toString();
        }
        // Try to change the owner of the file
        String newOwnerChangeResults = setNewOwner(newOwner);
        if (newOwnerChangeResults.contains("Error")) {
            return newOwnerChangeResults;
        }
        // Try to change the permissions of the file
        String newPermissionsChangeResults = setNewPermissions(newOwner);
        if (newPermissionsChangeResults.contains("Error")) {
            return newPermissionsChangeResults;
        }
        // If we get here, both the owner and permissions were changed successfully
        String successMessage = String.format("Success: Changed owner and permissions of file %s", targetFilePath.toAbsolutePath());
        logFine(successMessage);
        return successMessage;
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple(), dev.filechampion.filechampion4j.FileAclHelper.logFine(), dev.filechampion.filechampion4j.FileAclHelper.newOwnerUsername, dev.filechampion.filechampion4j.FileAclHelper.newPermissions, dev.filechampion.filechampion4j.FileAclHelper.setNewOwner(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissions(), and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Referenced by dev.filechampion.filechampion4j.FileValidator.saveFileToOutputDir().
getUserPrinciple()
UserPrincipal dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple (Path targetFilePath, String newOwnerUsername) private
Definition at line 98 of file FileAclHelper.java.
{
        try {
            return targetFilePath.getFileSystem()
            .getUserPrincipalLookupService()
            .lookupPrincipalByName(newOwnerUsername);
        } catch (Exception e) {
            errMsg.replace(0, errMsg.length(), "Error: Exception getting user principal: ").append(e.getMessage());
            logSevere(errMsg.toString());
            return null;
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.logSevere(), dev.filechampion.filechampion4j.FileAclHelper.newOwnerUsername, and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl().
logFine()
void dev.filechampion.filechampion4j.FileAclHelper.logFine (String message) private
Definition at line 41 of file FileAclHelper.java.
{
        if (LOGGER.isLoggable(Level.FINE )) {
            LOGGER.fine(message);
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileAclHelper.setNewOwner(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
logSevere()
void dev.filechampion.filechampion4j.FileAclHelper.logSevere (String message) private
Definition at line 36 of file FileAclHelper.java.
{
        if (LOGGER.isLoggable(Level.SEVERE)) {
            LOGGER.severe(message);
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.LOGGER.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple(), dev.filechampion.filechampion4j.FileAclHelper.setNewOwner(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
setNewOwner()
String dev.filechampion.filechampion4j.FileAclHelper.setNewOwner (UserPrincipal newOwner) private
Definition at line 111 of file FileAclHelper.java.
{
        try {
            // Change the owner of the file
            Files.setOwner(targetFilePath, newOwner);
            errMsg.replace(0, errMsg.length(), "Success: Changed owner of file").append(targetFilePath.toAbsolutePath()).append(" to ").append(newOwnerUsername);
            logFine(errMsg.toString());
            return errMsg.toString();
        } catch (AccessDeniedException e) {
            errMsg.replace(0, errMsg.length(), "Error: Access denied while changing file owner: ").append(e.getMessage());
            logSevere(errMsg.toString());
            return errMsg.toString();
        } catch (FileSystemException e) {
            errMsg.replace(0, errMsg.length(), "Error: File system error while changing file owner: ").append(e.getMessage());
            logSevere(errMsg.toString());
            return errMsg.toString();
        }
        catch (Exception e) {
            errMsg.replace(0, errMsg.length(), "Error: Exception while changing file owner: ").append(e.getMessage());
            logSevere(errMsg.toString());
            return errMsg.toString();
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.logFine(), dev.filechampion.filechampion4j.FileAclHelper.logSevere(), dev.filechampion.filechampion4j.FileAclHelper.newOwnerUsername, and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl().
setNewPermissions()
String dev.filechampion.filechampion4j.FileAclHelper.setNewPermissions (UserPrincipal newOwner) private
Definition at line 135 of file FileAclHelper.java.
{
        String os = System.getProperty("os.name");
        if (os.startsWith("Windows")) {
            return setNewPermissionsWindows(newOwner);
        } else {
            return setNewPermissionsUnix();
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
Referenced by dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl().
setNewPermissionsUnix()
String dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix () private
Definition at line 197 of file FileAclHelper.java.
{
        String statusMessage;
        // Build the new permissions
        Set<PosixFilePermission> permissions = new HashSet<>();
        if (newPermissions.contains("r")) {
            permissions.add(PosixFilePermission.OWNER_READ);
        }
        if (newPermissions.contains("w")) {
            permissions.add(PosixFilePermission.OWNER_WRITE);
        }
        if (newPermissions.contains("x")) {
            permissions.add(PosixFilePermission.OWNER_EXECUTE);
        }
        // Change the permissions of the file using POSIX
        try {
            statusMessage = String.format("Attempting to change permissions to %s", permissions);
            logFine(statusMessage);
            Files.setPosixFilePermissions(targetFilePath.toAbsolutePath(), permissions);
            errMsg.replace(0, errMsg.length(), "Success: Changed permissions of file").append(targetFilePath.toAbsolutePath()).append(" to ").append(permissions);
            logFine(errMsg.toString());
            return errMsg.toString();
        } catch (Exception e) {
            errMsg.replace(0, errMsg.length(), "Error: Exception setting permissions on file with POSIX: ")
                .append(targetFilePath.toAbsolutePath())
                .append(", ")
                .append(e.getMessage());
            logSevere(errMsg.toString());
            return errMsg.toString();
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.logFine(), dev.filechampion.filechampion4j.FileAclHelper.logSevere(), dev.filechampion.filechampion4j.FileAclHelper.newPermissions, and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.setNewPermissions().
setNewPermissionsWindows()
String dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows (UserPrincipal newOwner) private
Definition at line 145 of file FileAclHelper.java.
{
        try {
            String statusMessage;
            // Change the permissions of the file using ACLs
            AclFileAttributeView aclView = Files.getFileAttributeView(targetFilePath, AclFileAttributeView.class);
            AclEntryPermission readPermission = AclEntryPermission.READ_DATA;
            AclEntryPermission writePermission = AclEntryPermission.WRITE_DATA;
            AclEntryPermission executePermission = AclEntryPermission.EXECUTE;
            AclEntryType allow = AclEntryType.ALLOW;
            EnumSet<AclEntryPermission> actualPermissions = EnumSet.noneOf(AclEntryPermission.class);
            if (newPermissions.contains("r")) {
                actualPermissions.add(readPermission);
            }
            if (newPermissions.contains("w")) {
                actualPermissions.add(writePermission);
            }
            if (newPermissions.contains("x")) {
                actualPermissions.add(executePermission);
            }
            statusMessage = String.format("Attempting to change permissions to %s", actualPermissions);
            logFine(statusMessage);
            // Create the new ACL entry
            AclEntry aclEntry = AclEntry.newBuilder()
                    .setType(allow)
                    .setPrincipal(newOwner)
                    .setPermissions(actualPermissions)
                    .build();
            // Get the existing ACL and add the new ACL entries
            List<AclEntry> acl = new ArrayList<>();
            acl.add(aclEntry);
            // Set the new ACL
            aclView.setAcl(acl);
            errMsg.replace(0, errMsg.length(), "Success: Changed permissions of file").append(targetFilePath.toAbsolutePath()).append(" to ").append(actualPermissions);
            logFine(errMsg.toString());
            return errMsg.toString();
        } catch (Exception e) {
            errMsg.replace(0, errMsg.length(), "Error: Exception setting permissions on file with ACL: ")
                .append(targetFilePath.toAbsolutePath())
                .append(", ")
                .append(e.getMessage());
            logSevere(errMsg.toString());
            return errMsg.toString();
        }
    }
References dev.filechampion.filechampion4j.FileAclHelper.errMsg, dev.filechampion.filechampion4j.FileAclHelper.logFine(), dev.filechampion.filechampion4j.FileAclHelper.logSevere(), dev.filechampion.filechampion4j.FileAclHelper.newPermissions, and dev.filechampion.filechampion4j.FileAclHelper.targetFilePath.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.setNewPermissions().
Member Data Documentation
errMsg
StringBuilder dev.filechampion.filechampion4j.FileAclHelper.errMsg = new StringBuilder() private
Definition at line 25 of file FileAclHelper.java.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.FileAclHelper(), dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple(), dev.filechampion.filechampion4j.FileAclHelper.setNewOwner(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
LOGGER
final Logger dev.filechampion.filechampion4j.FileAclHelper.LOGGER = Logger.getLogger(FileAclHelper.class.getName()) static private
Definition at line 35 of file FileAclHelper.java.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.logFine(), and dev.filechampion.filechampion4j.FileAclHelper.logSevere().
newOwnerUsername
String dev.filechampion.filechampion4j.FileAclHelper.newOwnerUsername private
Definition at line 24 of file FileAclHelper.java.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.FileAclHelper(), dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple(), and dev.filechampion.filechampion4j.FileAclHelper.setNewOwner().
newPermissions
String dev.filechampion.filechampion4j.FileAclHelper.newPermissions private
Definition at line 23 of file FileAclHelper.java.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.FileAclHelper(), dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
targetFilePath
Path dev.filechampion.filechampion4j.FileAclHelper.targetFilePath private
Definition at line 22 of file FileAclHelper.java.
Referenced by dev.filechampion.filechampion4j.FileAclHelper.FileAclHelper(), dev.filechampion.filechampion4j.FileAclHelper.changeFileAcl(), dev.filechampion.filechampion4j.FileAclHelper.getUserPrinciple(), dev.filechampion.filechampion4j.FileAclHelper.setNewOwner(), dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsUnix(), and dev.filechampion.filechampion4j.FileAclHelper.setNewPermissionsWindows().
The documentation for this class was generated from the following file:
src/main/java/dev/filechampion/filechampion4j/FileAclHelper.java