name: Feature Branch Tests

on:
  pull_request:
    branches:
      - feature-*

jobs:
  compare_results:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and generate result.txt
      run: mvn clean test -Dtest="FileValidatorBenchRun"
    - name: Clone master branch
      run: |
        cd ..
        git clone -b master --single-branch https://github.com/povimd9/FileChampion4j.git master-branch
    - name: Copy result.txt to master branch
      run: \cp -r feature-*/benchmarks/benchResults.txt master-branch/benchmarks/
    - name: Compare test results
      working-directory: master-branch
      run: |
        mvn clean test -Dtest="FileValidatorBenchRun"
        mvn test -Dtest="FileValidatorBenchCompare"
      if: ${{ success() }}
