name: CI

on:
  workflow_run:
    workflows:
      - master_build_workflow
    types:
      - completed
    branches:
      - master
      - feature-*

permissions:
  contents: write

jobs:
  bench-and-package:
    name: Build, Bench, and Package
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'corretto'
        env:
            JAVA8_HOME: ${{ env.JAVA_HOME }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
        env:
            JAVA11_HOME: ${{ env.JAVA_HOME }}
            
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
        env:
            JAVA17_HOME: ${{ env.JAVA_HOME }}

      - name: Make mvnw executable
        run: |
          chmod +x ${{ github.workspace }}/mvnw

      - name: Build with Maven
        run: mvn -B -U clean install --file pom-release.xml "-Djava8.home=$JAVA8_HOME" "-D=java11.home=$JAVA11_HOME" "-Djava17.home=$JAVA17_HOME"

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "povimd9"
          git config --global user.email "povimd9@users.noreply.github.com"
          git add target/FileChampion4j.jar
          git add target/FileChampion4j-jar-with-dependencies.jar
          git commit -m "Add new package dist JARs"
          git push

