name: CI

on:
  workflow_run:
    workflows:
      - master_build_workflow
    types:
      - completed
    branches:
      - master

permissions:
  contents: write

jobs:
  check-master-build-result:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps: 
      - run: exit 1
      
  bench-and-package:
    name: Build, Bench, and Package
    runs-on: ubuntu-20.04
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'corretto'
        env:
          JAVA8_HOME: ${{ env.JAVA_HOME }}

      - name: Checkout latest file from master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Make mvnw executable
        run: |
          chmod +x ${{ github.workspace }}/mvnw

      - name: Build with Maven
        env:
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
        run: mvn -B -U clean install --file pom-release.xml "-Djava8.home=$JAVA8_HOME"

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
      - name: Create version branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LATEST_VER: ${{ vars.LATEST_VERSION }}
        run: |
          git config --global user.name "povimd9"
          git config --global user.email "povimd9@users.noreply.github.com"
          git checkout -b "release-$LATEST_VER"
          git add target/dependency-list.txt
          git add target/FileChampion4j.jar
          git add target/FileChampion4j-jar-with-dependencies.jar
          git commit -m "Add new package dist JARs"
          git push -f --set-upstream origin "release-$LATEST_VER"
          
