name: Master Workflow

on:
  push:
    branches:
      - master
  pull_request:
    workflow_dispatch:
      branches:
        - master
        - feature/*

jobs:
  build-and-test-on-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SafeFilez/SafeFilez/.github/workflows/maven_nix.yml@master

  build-and-test-on-macos:
    needs: build-and-test-on-nix
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SafeFilez/SafeFilez/.github/workflows/maven_macos.yml@master

  build-and-test-on-windows:
    needs: build-and-test-on-macos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SafeFilez/SafeFilez/.github/workflows/maven_win.yml@master

  run-codeql-analysis:
    needs: build-and-test-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SafeFilez/SafeFilez/.github/workflows/codeql.yml@master

  upload-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: advanced-security/maven-dependency-submission-action@v3.0.0

  pin-actions-to-commit-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: SafeFilez/SafeFilez/.github/workflows/pin_actions_to_commit_sha.yml@master