name: master_workflow

on:
  push:
    branches:
      - master
  pull_request:
    workflow_dispatch:
      branches:
        - master
        - feature/*

permissions:
  contents: write
  pages: write

jobs:
  check-out-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build-and-test-on-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/maven_nix.yml

  build-and-test-on-macos:
    needs: build-and-test-on-nix
    runs-on: macos-latest
    steps:
      - uses: ./.github/workflows/maven_macos.yml

  build-and-test-on-windows:
    needs: build-and-test-on-macos
    runs-on: windows-latest
    steps:
      - uses: ./.github/workflows/maven_win.yml

  run-codeql-analysis:
    needs: build-and-test-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/codeql.yml

  pin-actions-to-commit-sha:
    needs: build-and-test-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/pin_actions_to_commit_sha.yml