name: Master Workflow

on:
  push:
    branches:
      - main
    pull_request:
      workflow_dispatch:
        branches:
          - main
          - feature/*

jobs:
  build-and-test-on-nix-mac:
    steps:
      - uses: maven_nix.yml@master

  build-and-test-on-windows:
    steps:
      - uses: maven_win.yml@master
    requires:
      - build-and-test-on-nix-mac

    run-codeql-analysis:
      steps:
        - uses: codeql.yml@master
      requires:
        - build-and-test-on-windows

  upload-dependency-graph:
    steps:
      - uses: advanced-security/maven-dependency-submission-action@v3.0.0
    requires:
      - build-and-test-on-windows

  pin-actions-to-commit-sha:
    steps:
      - uses: pin_actions_to_commit_sha.yml@master
    requires:
      - upload-dependency-graph