name: Build_MAC_Maven

on:
  pull_request:
    workflow_dispatch:
      branches:
        - master
        - feature/*

permissions: 
  contents: write
  pages: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make mvnw executable (Linux)
        run: |
          chmod +x ${{ github.workspace }}/mvnw

      - name: Build with Maven
        run: mvn -B -U package --file pom.xml
