name: Publish filechampion to the Maven Central Repository
on:
  release:
    types:
      - created
      - edited

jobs:
  package-and-deploy:
    name: Build, Bench, and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3
      
      - name: Set up JDK 8 and Maven Central Repo
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
        env:
          JAVA8_HOME: ${{ env.JAVA_HOME }}

      - name: Make mvnw executable
        run: |
          chmod +x ${{ github.workspace }}/mvnw

      - name: Build, Sign, and Publish
        env:
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
          GPG_CERT_PASS: ${{ secrets.GPG_CERT_PASS }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: |
          echo ${{ secrets.GPG_OWNERTRUST }} > gpg_owner_trust.b64
          openssl base64 -d -A -in gpg_owner_trust.b64 > gpg_owner_trust.txt
          echo ${{ secrets.GPG_SECRET_KEYS }} > gpg_certs.b64
          openssl base64 -d -A -in gpg_certs.b64 > gpg_certs.asc
          gpg --import-ownertrust gpg_owner_trust.txt
          gpg --import --no-tty --batch --yes gpg_certs.asc
          echo ${{ secrets.BLUMO_JKS }} > blumo_jks.b64
          openssl base64 -d -A -in blumo_jks.b64 > blumo.jks
          mvn -B -U clean install --file pom-deploy.xml "-Djava8.home=$JAVA8_HOME" "-Dsignkey.pass=$SIGN_KEY_PASS" "-Dblumo.jks=blumo.jks" "-Dgpg.passphrase=$GPG_CERT_PASS"
          mvn -B deploy --file pom-deploy.xml "-Djava8.home=$JAVA8_HOME" "-Dsignkey.pass=$SIGN_KEY_PASS" "-Dblumo.jks=blumo.jks" "-Dgpg.passphrase=$GPG_CERT_PASS"
